In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

In [2]:
path_to_hotel_booking  = Path(r'C:\Users\konta\Documents\DIV_Academy\Module2(From_29_nov)\data\hotel_bookings.csv')

In [3]:
df = pd.read_csv(path_to_hotel_booking)

In [4]:
df.shape

(119390, 32)

In [5]:
df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date'],
      dtype='object')

In [6]:
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(16), object(12)
memory usage: 29.1+ MB

In [8]:
summary = pd.DataFrame({
    "dtype": df.dtypes,
    "missing": df.isnull().sum()
}).reset_index()
summary

                             index    dtype  missing
0                            hotel   object        0
1                      is_canceled    int64        0
2                        lead_time    int64        0
3                arrival_date_year    int64        0
4               arrival_date_month   object        0
5         arrival_date_week_number    int64        0
6        arrival_date_day_of_month    int64        0
7          stays_in_weekend_nights    int64        0
8             stays_in_week_nights    int64        0
9                           adults    int64        0
10                        children  float64        4
11                          babies    int64        0
12                            meal   object        0
13                         country   object      488
14                  market_segment   object        0
15            distribution_channel   object        0
16               is_repeated_guest    int64        0
17          previous_cancellations    int64        0
18  previous_bookings_not_canceled    int64        0
19              reserved_room_type   object        0
20              assigned_room_type   object        0
21                 booking_changes    int64        0
22                    deposit_type   object        0
23                           agent  float64    16340
24                         company  float64   112593
25            days_in_waiting_list    int64        0
26                   customer_type   object        0
27                             adr  float64        0
28     required_car_parking_spaces    int64        0
29       total_of_special_requests    int64        0
30              reservation_status   object        0
31         reservation_status_date   object        0

In [9]:
summary['missing_pct'] = (summary['missing'] / len(df)) * 100
summary = summary.sort_values('missing_pct', ascending=False)
summary

                             index    dtype  missing  missing_pct
24                         company  float64   112593    94.306893
23                           agent  float64    16340    13.686238
13                         country   object      488     0.408744
10                        children  float64        4     0.003350
4               arrival_date_month   object        0     0.000000
5         arrival_date_week_number    int64        0     0.000000
0                            hotel   object        0     0.000000
1                      is_canceled    int64        0     0.000000
7          stays_in_weekend_nights    int64        0     0.000000
6        arrival_date_day_of_month    int64        0     0.000000
9                           adults    int64        0     0.000000
8             stays_in_week_nights    int64        0     0.000000
11                          babies    int64        0     0.000000
12                            meal   object        0     0.000000
2                        lead_time    int64        0     0.000000
3                arrival_date_year    int64        0     0.000000
15            distribution_channel   object        0     0.000000
14                  market_segment   object        0     0.000000
18  previous_bookings_not_canceled    int64        0     0.000000
16               is_repeated_guest    int64        0     0.000000
19              reserved_room_type   object        0     0.000000
20              assigned_room_type   object        0     0.000000
21                 booking_changes    int64        0     0.000000
17          previous_cancellations    int64        0     0.000000
22                    deposit_type   object        0     0.000000
25            days_in_waiting_list    int64        0     0.000000
26                   customer_type   object        0     0.000000
27                             adr  float64        0     0.000000
28     required_car_parking_spaces    int64        0     0.000000
29       total_of_special_requests    int64        0     0.000000
30              reservation_status   object        0     0.000000
31         reservation_status_date   object        0     0.000000

In [10]:
drop_cols = summary.loc[summary['missing_pct'] > 70, "index"]
df = df.drop(columns=drop_cols)

In [11]:
df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date'],
      dtype='object')

In [12]:
df['children'] = df['children'].fillna(0)

In [13]:
df['country'] = df['country'].fillna("Unknown")

In [14]:
summary = pd.DataFrame({
    "dtype": df.dtypes,
    "missing": df.isnull().sum()
}).reset_index()
summary

                             index    dtype  missing
0                            hotel   object        0
1                      is_canceled    int64        0
2                        lead_time    int64        0
3                arrival_date_year    int64        0
4               arrival_date_month   object        0
5         arrival_date_week_number    int64        0
6        arrival_date_day_of_month    int64        0
7          stays_in_weekend_nights    int64        0
8             stays_in_week_nights    int64        0
9                           adults    int64        0
10                        children  float64        0
11                          babies    int64        0
12                            meal   object        0
13                         country   object        0
14                  market_segment   object        0
15            distribution_channel   object        0
16               is_repeated_guest    int64        0
17          previous_cancellations    int64        0
18  previous_bookings_not_canceled    int64        0
19              reserved_room_type   object        0
20              assigned_room_type   object        0
21                 booking_changes    int64        0
22                    deposit_type   object        0
23                           agent  float64    16340
24            days_in_waiting_list    int64        0
25                   customer_type   object        0
26                             adr  float64        0
27     required_car_parking_spaces    int64        0
28       total_of_special_requests    int64        0
29              reservation_status   object        0
30         reservation_status_date   object        0

In [15]:
summary['missing_pct'] = (summary['missing'] / len(df)) * 100
summary = summary.sort_values('missing_pct', ascending=False)
summary

                             index    dtype  missing  missing_pct
23                           agent  float64    16340    13.686238
1                      is_canceled    int64        0     0.000000
0                            hotel   object        0     0.000000
3                arrival_date_year    int64        0     0.000000
4               arrival_date_month   object        0     0.000000
5         arrival_date_week_number    int64        0     0.000000
2                        lead_time    int64        0     0.000000
7          stays_in_weekend_nights    int64        0     0.000000
8             stays_in_week_nights    int64        0     0.000000
9                           adults    int64        0     0.000000
10                        children  float64        0     0.000000
11                          babies    int64        0     0.000000
12                            meal   object        0     0.000000
13                         country   object        0     0.000000
6        arrival_date_day_of_month    int64        0     0.000000
14                  market_segment   object        0     0.000000
15            distribution_channel   object        0     0.000000
17          previous_cancellations    int64        0     0.000000
16               is_repeated_guest    int64        0     0.000000
19              reserved_room_type   object        0     0.000000
20              assigned_room_type   object        0     0.000000
21                 booking_changes    int64        0     0.000000
18  previous_bookings_not_canceled    int64        0     0.000000
22                    deposit_type   object        0     0.000000
24            days_in_waiting_list    int64        0     0.000000
25                   customer_type   object        0     0.000000
26                             adr  float64        0     0.000000
27     required_car_parking_spaces    int64        0     0.000000
28       total_of_special_requests    int64        0     0.000000
29              reservation_status   object        0     0.000000
30         reservation_status_date   object        0     0.000000

In [16]:
df["agent"] = df["agent"].fillna(0)
df["agent"] = df["agent"].astype(int)

In [17]:
df['has_agent'] = (df['agent'] != 0).astype(int)

In [18]:
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,has_agent
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,0,0,Transient,0.00,0,0,Check-Out,2015-07-01,0
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,0,0,Transient,0.00,0,0,Check-Out,2015-07-01,0
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,0,0,Transient,75.00,0,0,Check-Out,2015-07-02,0
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304,0,Transient,75.00,0,0,Check-Out,2015-07-02,1
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240,0,Transient,98.00,0,1,Check-Out,2015-07-03,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,No Deposit,394,0,Transient,96.14,0,0,Check-Out,2017-09-06,1
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,No Deposit,9,0,Transient,225.43,0,2,Check-Out,2017-09-07,1
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,No Deposit,9,0,Transient,157.71,0,4,Check-Out,2017-09-07,1
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,No Deposit,89,0,Transient,104.40,0,0,Check-Out,2017-09-07,1
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,No Deposit,9,0,Transient,151.20,0,2,Check-Out,2017-09-07,1

In [19]:
summary = pd.DataFrame({
    "dtype": df.dtypes,
    "missing": df.isnull().sum()
}).reset_index()
summary

                             index    dtype  missing
0                            hotel   object        0
1                      is_canceled    int64        0
2                        lead_time    int64        0
3                arrival_date_year    int64        0
4               arrival_date_month   object        0
5         arrival_date_week_number    int64        0
6        arrival_date_day_of_month    int64        0
7          stays_in_weekend_nights    int64        0
8             stays_in_week_nights    int64        0
9                           adults    int64        0
10                        children  float64        0
11                          babies    int64        0
12                            meal   object        0
13                         country   object        0
14                  market_segment   object        0
15            distribution_channel   object        0
16               is_repeated_guest    int64        0
17          previous_cancellations    int64        0
18  previous_bookings_not_canceled    int64        0
19              reserved_room_type   object        0
20              assigned_room_type   object        0
21                 booking_changes    int64        0
22                    deposit_type   object        0
23                           agent    int64        0
24            days_in_waiting_list    int64        0
25                   customer_type   object        0
26                             adr  float64        0
27     required_car_parking_spaces    int64        0
28       total_of_special_requests    int64        0
29              reservation_status   object        0
30         reservation_status_date   object        0
31                       has_agent    int64        0

In [20]:
df['children'] = df['children'].astype(int)

In [21]:
df['total_nights'] = df['stays_in_weekend_nights'] + df['stays_in_week_nights']
df['total_guests'] = df['adults'] + df['children'] + df['babies']

In [22]:
df['arrival_date'] = pd.to_datetime(
    df['arrival_date_year'].astype(str) + '-' +
    df['arrival_date_month'] + '-' +
    df['arrival_date_day_of_month'].astype(str),
    errors='coerce'
)

In [23]:
df = df.drop(columns=['arrival_date_year', 'arrival_date_month', 'arrival_date_day_of_month'])

In [24]:
df

,hotel,is_canceled,lead_time,arrival_date_week_number,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,...,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,has_agent,total_nights,total_guests,arrival_date
0,Resort Hotel,0,342,27,0,0,2,0,0,BB,...,Transient,0.00,0,0,Check-Out,2015-07-01,0,0,2,2015-07-01
1,Resort Hotel,0,737,27,0,0,2,0,0,BB,...,Transient,0.00,0,0,Check-Out,2015-07-01,0,0,2,2015-07-01
2,Resort Hotel,0,7,27,0,1,1,0,0,BB,...,Transient,75.00,0,0,Check-Out,2015-07-02,0,1,1,2015-07-01
3,Resort Hotel,0,13,27,0,1,1,0,0,BB,...,Transient,75.00,0,0,Check-Out,2015-07-02,1,1,1,2015-07-01
4,Resort Hotel,0,14,27,0,2,2,0,0,BB,...,Transient,98.00,0,1,Check-Out,2015-07-03,1,2,2,2015-07-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,35,2,5,2,0,0,BB,...,Transient,96.14,0,0,Check-Out,2017-09-06,1,7,2,2017-08-30
119386,City Hotel,0,102,35,2,5,3,0,0,BB,...,Transient,225.43,0,2,Check-Out,2017-09-07,1,7,3,2017-08-31
119387,City Hotel,0,34,35,2,5,2,0,0,BB,...,Transient,157.71,0,4,Check-Out,2017-09-07,1,7,2,2017-08-31
119388,City Hotel,0,109,35,2,5,2,0,0,BB,...,Transient,104.40,0,0,Check-Out,2017-09-07,1,7,2,2017-08-31
119389,City Hotel,0,205,35,2,7,2,0,0,HB,...,Transient,151.20,0,2,Check-Out,2017-09-07,1,9,2,2017-08-29

### What we did earlier 🤔✅🏆

🎉 What we accomplished

Dropped useless columns with >90% missing

Handled missing categorical values (country → "Unknown")

Cleaned agent

Filled missing with 0

Created has_agent flag (+ optional label)

No more missing values anywhere ✅

Converted arrival date columns into one clean arrival_date

Feature engineering:

total_nights

total_guests

booking_value

Optional labels for categorical flags (repeated_guest_label, has_agent_label)

Data types fixed for analysis

Dataset ready for analysis, ML, or GitHub

In [25]:
df.to_csv('Cleaned_Hotel_Bookings_Data.csv')