In [2]:
import pandas as pd
import numpy as np
from pathlib import Path

In [3]:
path_to_csv = Path(r'C:\Users\konta\Documents\DIV_Academy\Module2(From_29_nov)\data\dirty_cafe_sales.csv')

In [4]:
df = pd.read_csv(path_to_csv)

In [5]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [6]:
df_copy = df

In [7]:
df_copy.describe()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
count,10000,9667,9862,9821,9827,7421,6735,9841
unique,10000,10,7,8,19,5,4,367
top,TXN_1961373,Juice,5,3.0,6.0,Digital Wallet,Takeaway,UNKNOWN
freq,1,1171,2013,2429,979,2291,3022,159

In [8]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [9]:
summary = pd.DataFrame({
    "dtype": df_copy.dtypes,
    "missing": df_copy.isnull().sum()
}).reset_index()

summary

              index   dtype  missing
0    Transaction ID  object        0
1              Item  object      333
2          Quantity  object      138
3    Price Per Unit  object      179
4       Total Spent  object      173
5    Payment Method  object     2579
6          Location  object     3265
7  Transaction Date  object      159

In [10]:
summary['missing_pct'] = (summary['missing'] / len(df_copy)) * 100
summary = summary.sort_values('missing_pct', ascending=False)
summary

              index   dtype  missing  missing_pct
6          Location  object     3265        32.65
5    Payment Method  object     2579        25.79
1              Item  object      333         3.33
3    Price Per Unit  object      179         1.79
4       Total Spent  object      173         1.73
7  Transaction Date  object      159         1.59
2          Quantity  object      138         1.38
0    Transaction ID  object        0         0.00

In [11]:
df_copy[df_copy['Location'].isna()]

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-31
16,TXN_3765707,Sandwich,1,4.0,4.0,NaN,NaN,2023-06-10
23,TXN_2616390,Sandwich,2,4.0,8.0,NaN,NaN,2023-09-18
28,TXN_8467949,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-11
30,TXN_1736287,NaN,5,2.0,10.0,Digital Wallet,NaN,2023-06-02
...,...,...,...,...,...,...,...,...
9993,TXN_4766549,Smoothie,2,4.0,NaN,Cash,NaN,2023-10-20
9994,TXN_7851634,UNKNOWN,4,4.0,16.0,NaN,NaN,2023-01-08
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02

In [12]:
df_copy['Location'] = df_copy['Location'].fillna('No Location')

In [13]:
df_copy[df_copy['Location'].isna()]

Empty DataFrame
Columns: [Transaction ID, Item, Quantity, Price Per Unit, Total Spent, Payment Method, Location, Transaction Date]
Index: []

In [14]:
df_copy['Location'] = df_copy['Location'].replace('UNKNOWN', 'No Location')

In [15]:
df_copy[df_copy['Location'] == 'UNKNOWN']

Empty DataFrame
Columns: [Transaction ID, Item, Quantity, Price Per Unit, Total Spent, Payment Method, Location, Transaction Date]
Index: []

In [16]:
summary = pd.DataFrame({
    "dtype": df_copy.dtypes,
    "missing": df_copy.isnull().sum()
}).reset_index()

summary

              index   dtype  missing
0    Transaction ID  object        0
1              Item  object      333
2          Quantity  object      138
3    Price Per Unit  object      179
4       Total Spent  object      173
5    Payment Method  object     2579
6          Location  object        0
7  Transaction Date  object      159

In [17]:
summary['missing_pct'] = (summary['missing'] / len(df_copy)) * 100
summary = summary.sort_values('missing_pct', ascending=False)
summary

              index   dtype  missing  missing_pct
5    Payment Method  object     2579        25.79
1              Item  object      333         3.33
3    Price Per Unit  object      179         1.79
4       Total Spent  object      173         1.73
7  Transaction Date  object      159         1.59
2          Quantity  object      138         1.38
0    Transaction ID  object        0         0.00
6          Location  object        0         0.00

In [18]:
df_copy[df_copy['Payment Method'].isna()]

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
8,TXN_4717867,NaN,5,3.0,15.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5,4.0,20.0,NaN,In-store,2023-12-31
13,TXN_9437049,Cookie,5,1.0,5.0,NaN,Takeaway,2023-06-01
14,TXN_8915701,ERROR,2,1.5,3.0,NaN,In-store,2023-03-21
16,TXN_3765707,Sandwich,1,4.0,4.0,NaN,No Location,2023-06-10
...,...,...,...,...,...,...,...,...
9978,TXN_4302199,Tea,3,1.5,4.5,NaN,No Location,2023-02-16
9982,TXN_8567525,Cookie,2,1.0,2.0,NaN,Takeaway,2023-12-30
9985,TXN_3297457,Cake,2,3.0,6.0,NaN,No Location,2023-01-03
9994,TXN_7851634,UNKNOWN,4,4.0,16.0,NaN,No Location,2023-01-08
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,No Location,2023-08-30

In [19]:
df_copy['Payment Method'] = df_copy['Payment Method'].fillna('No payment method')

In [20]:
df_copy[df_copy['Payment Method'].isna()]

Empty DataFrame
Columns: [Transaction ID, Item, Quantity, Price Per Unit, Total Spent, Payment Method, Location, Transaction Date]
Index: []

In [21]:
df_copy['Payment Method'] = df_copy['Payment Method'].replace('UNKNOWN', 'No payment method')

In [22]:
df_copy[df_copy['Payment Method'] == 'UNKNOWN']

Empty DataFrame
Columns: [Transaction ID, Item, Quantity, Price Per Unit, Total Spent, Payment Method, Location, Transaction Date]
Index: []

In [23]:
summary = pd.DataFrame({
    "dtype": df_copy.dtypes,
    "missing": df_copy.isnull().sum()
}).reset_index()

summary

              index   dtype  missing
0    Transaction ID  object        0
1              Item  object      333
2          Quantity  object      138
3    Price Per Unit  object      179
4       Total Spent  object      173
5    Payment Method  object        0
6          Location  object        0
7  Transaction Date  object      159

In [24]:
summary['missing_pct'] = (summary['missing'] / len(df_copy)) * 100
summary = summary.sort_values('missing_pct', ascending=False)
summary

              index   dtype  missing  missing_pct
1              Item  object      333         3.33
3    Price Per Unit  object      179         1.79
4       Total Spent  object      173         1.73
7  Transaction Date  object      159         1.59
2          Quantity  object      138         1.38
0    Transaction ID  object        0         0.00
5    Payment Method  object        0         0.00
6          Location  object        0         0.00

In [25]:
df_copy['Item']

0         Coffee
1           Cake
2         Cookie
3          Salad
4         Coffee
          ...
9995      Coffee
9996         NaN
9997      Coffee
9998      Cookie
9999    Sandwich
Name: Item, Length: 10000, dtype: object

In [26]:
df_copy[df_copy['Item'].isna()]

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
8,TXN_4717867,NaN,5,3.0,15.0,No payment method,Takeaway,2023-07-28
30,TXN_1736287,NaN,5,2.0,10.0,Digital Wallet,No Location,2023-06-02
61,TXN_8051289,NaN,1,3.0,3.0,No payment method,In-store,2023-10-09
72,TXN_6044979,NaN,1,1.0,1.0,Cash,In-store,2023-12-08
89,TXN_4132730,NaN,5,1.0,5.0,No payment method,In-store,2023-03-12
...,...,...,...,...,...,...,...,...
9820,TXN_8751702,NaN,5,NaN,15.0,Cash,No Location,2023-02-13
9855,TXN_3740505,NaN,2,1.5,3.0,No payment method,No Location,2023-11-21
9876,TXN_3105633,NaN,1,2.0,2.0,No payment method,In-store,2023-03-30
9885,TXN_4659954,NaN,3,4.0,12.0,Credit Card,In-store,NaN
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,No Location,2023-06-02

In [27]:
df_copy['Item'] = df_copy['Item'].fillna('Unwritten Item')

In [28]:
df_copy

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,No payment method,No Location,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,No payment method,No Location,2023-08-30
9996,TXN_9659401,Unwritten Item,3,NaN,3.0,Digital Wallet,No Location,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,No Location,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,No Location,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [29]:
df_copy[df_copy['Item'] == 'ERROR']

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
14,TXN_8915701,ERROR,2,1.5,3.0,No payment method,In-store,2023-03-21
69,TXN_8471743,ERROR,5,3.0,15.0,Digital Wallet,In-store,2023-04-06
88,TXN_9487821,ERROR,1,5.0,5.0,Digital Wallet,Takeaway,2023-05-24
118,TXN_4633784,ERROR,5,NaN,15.0,No payment method,In-store,2023-02-06
211,TXN_6717827,ERROR,3,5.0,15.0,Digital Wallet,No Location,2023-11-15
...,...,...,...,...,...,...,...,...
9910,TXN_2338617,ERROR,2,3.0,6.0,Digital Wallet,No Location,2023-01-12
9918,TXN_2292088,ERROR,1,4.0,4.0,Digital Wallet,Takeaway,2023-03-04
9951,TXN_4122925,ERROR,4,1.0,4.0,No payment method,Takeaway,2023-10-20
9958,TXN_4125474,ERROR,2,5.0,10.0,Credit Card,In-store,2023-08-02
9981,TXN_4583012,ERROR,5,4.0,20.0,Digital Wallet,No Location,2023-02-27

In [30]:
df_copy['Item'] = df_copy['Item'].replace('UNKNOWN', 'Unwritten Item')

In [31]:
df_copy['Item'] = df_copy['Item'].replace('ERROR', 'Unwritten Item')

In [32]:
summary = pd.DataFrame({
    "dtype": df_copy.dtypes,
    "missing": df_copy.isnull().sum()
}).reset_index()

summary

              index   dtype  missing
0    Transaction ID  object        0
1              Item  object        0
2          Quantity  object      138
3    Price Per Unit  object      179
4       Total Spent  object      173
5    Payment Method  object        0
6          Location  object        0
7  Transaction Date  object      159

In [33]:
summary['missing_pct'] = (summary['missing'] / len(df_copy)) * 100
summary = summary.sort_values('missing_pct', ascending=False)
summary

              index   dtype  missing  missing_pct
3    Price Per Unit  object      179         1.79
4       Total Spent  object      173         1.73
7  Transaction Date  object      159         1.59
2          Quantity  object      138         1.38
0    Transaction ID  object        0         0.00
1              Item  object        0         0.00
5    Payment Method  object        0         0.00
6          Location  object        0         0.00

In [34]:
df_copy[df_copy['Price Per Unit'].isna()]

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
56,TXN_3578141,Cake,5,NaN,15.0,No payment method,Takeaway,2023-06-27
65,TXN_4987129,Sandwich,3,NaN,NaN,No payment method,In-store,2023-10-20
85,TXN_8035512,Tea,3,NaN,4.5,Cash,No Location,2023-10-29
104,TXN_7447872,Juice,2,NaN,6.0,No payment method,No Location,NaN
118,TXN_4633784,Unwritten Item,5,NaN,15.0,No payment method,In-store,2023-02-06
...,...,...,...,...,...,...,...,...
9820,TXN_8751702,Unwritten Item,5,NaN,15.0,Cash,No Location,2023-02-13
9893,TXN_3809533,Juice,2,NaN,ERROR,Digital Wallet,Takeaway,2023-02-02
9924,TXN_5981429,Juice,2,NaN,6.0,Digital Wallet,No Location,2023-12-24
9996,TXN_9659401,Unwritten Item,3,NaN,3.0,Digital Wallet,No Location,2023-06-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,No Location,2023-12-02

In [35]:
df_copy[df_copy['Price Per Unit'] == 'ERROR']

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
68,TXN_8427104,Salad,2,ERROR,10.0,No payment method,In-store,2023-10-27
196,TXN_3800182,Tea,2,ERROR,3.0,Cash,In-store,2023-10-26
212,TXN_9089898,Salad,3,ERROR,15.0,Credit Card,No Location,2023-01-11
213,TXN_8587583,Cake,1,ERROR,3.0,No payment method,No Location,2023-10-01
289,TXN_3495950,Unwritten Item,4,ERROR,6.0,Credit Card,In-store,2023-02-19
...,...,...,...,...,...,...,...,...
9533,TXN_4434185,Smoothie,5,ERROR,20.0,Credit Card,Takeaway,2023-04-30
9605,TXN_9397870,Cake,2,ERROR,6.0,No payment method,No Location,2023-05-23
9649,TXN_2509803,Coffee,1,ERROR,2.0,No payment method,No Location,2023-02-22
9717,TXN_3334632,Unwritten Item,1,ERROR,2.0,Credit Card,Takeaway,2023-11-20
9753,TXN_3507013,Juice,1,ERROR,3.0,Digital Wallet,In-store,2023-01-16

In [36]:
df_copy[df_copy['Price Per Unit'] == 'UNKNOWN']

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
140,TXN_2484241,Cake,3,UNKNOWN,9.0,Digital Wallet,No Location,2023-07-19
147,TXN_9336980,Salad,4,UNKNOWN,20.0,Cash,In-store,2023-06-06
161,TXN_7965998,Juice,1,UNKNOWN,3.0,Credit Card,In-store,2023-11-02
162,TXN_9238666,Cookie,1,UNKNOWN,1.0,ERROR,Takeaway,2023-07-31
228,TXN_9350833,Cake,1,UNKNOWN,3.0,Cash,Takeaway,2023-01-17
...,...,...,...,...,...,...,...,...
9742,TXN_8077812,Salad,5,UNKNOWN,25.0,Cash,In-store,2023-01-16
9755,TXN_3092390,Sandwich,3,UNKNOWN,12.0,No payment method,In-store,2023-07-24
9796,TXN_8191202,Cookie,2,UNKNOWN,2.0,Digital Wallet,In-store,2023-01-14
9926,TXN_2464706,Cake,4,UNKNOWN,12.0,Digital Wallet,Takeaway,2023-11-09
9961,TXN_2153100,Tea,2,UNKNOWN,3.0,Cash,No Location,2023-12-29

In [37]:
df_copy['Price Per Unit'] = df_copy['Price Per Unit'].replace('UNKNOWN', 0)

In [38]:
df_copy['Price Per Unit'] = df_copy['Price Per Unit'].replace('ERROR', 0)

In [39]:
df_copy['Price Per Unit'] = df_copy['Price Per Unit'].fillna(0)

In [40]:
summary = pd.DataFrame({
    "dtype": df_copy.dtypes,
    "missing": df_copy.isnull().sum()
}).reset_index()

summary

              index   dtype  missing
0    Transaction ID  object        0
1              Item  object        0
2          Quantity  object      138
3    Price Per Unit  object        0
4       Total Spent  object      173
5    Payment Method  object        0
6          Location  object        0
7  Transaction Date  object      159

In [41]:
summary['missing_pct'] = (summary['missing'] / len(df_copy)) * 100
summary = summary.sort_values('missing_pct', ascending=False)
summary

              index   dtype  missing  missing_pct
4       Total Spent  object      173         1.73
7  Transaction Date  object      159         1.59
2          Quantity  object      138         1.38
0    Transaction ID  object        0         0.00
3    Price Per Unit  object        0         0.00
1              Item  object        0         0.00
5    Payment Method  object        0         0.00
6          Location  object        0         0.00

In [42]:
df_copy['Total Spent'] = df_copy['Total Spent'].fillna(0)

In [43]:
df_copy['Total Spent'] = df_copy['Total Spent'].replace('UNKNOWN', 0)

In [44]:
df_copy['Total Spent'] = df_copy['Total Spent'].replace('ERROR', 0)

In [45]:
summary = pd.DataFrame({
    "dtype": df_copy.dtypes,
    "missing": df_copy.isnull().sum()
}).reset_index()

summary

              index   dtype  missing
0    Transaction ID  object        0
1              Item  object        0
2          Quantity  object      138
3    Price Per Unit  object        0
4       Total Spent  object        0
5    Payment Method  object        0
6          Location  object        0
7  Transaction Date  object      159

In [46]:
summary['missing_pct'] = (summary['missing'] / len(df_copy)) * 100
summary = summary.sort_values('missing_pct', ascending=False)
summary

              index   dtype  missing  missing_pct
7  Transaction Date  object      159         1.59
2          Quantity  object      138         1.38
1              Item  object        0         0.00
0    Transaction ID  object        0         0.00
3    Price Per Unit  object        0         0.00
4       Total Spent  object        0         0.00
5    Payment Method  object        0         0.00
6          Location  object        0         0.00

In [47]:
df_copy['Quantity'] = df_copy['Quantity'].fillna(0)

In [48]:
df_copy['Quantity'] = df_copy['Quantity'].replace('UNKNOWN', 0)

In [49]:
df_copy['Quantity'] = df_copy['Quantity'].replace('ERROR', 0)

In [50]:
summary = pd.DataFrame({
    "dtype": df_copy.dtypes,
    "missing": df_copy.isnull().sum()
}).reset_index()

summary

              index   dtype  missing
0    Transaction ID  object        0
1              Item  object        0
2          Quantity  object        0
3    Price Per Unit  object        0
4       Total Spent  object        0
5    Payment Method  object        0
6          Location  object        0
7  Transaction Date  object      159

In [51]:
summary['missing_pct'] = (summary['missing'] / len(df_copy)) * 100
summary = summary.sort_values('missing_pct', ascending=False)
summary

              index   dtype  missing  missing_pct
7  Transaction Date  object      159         1.59
0    Transaction ID  object        0         0.00
2          Quantity  object        0         0.00
1              Item  object        0         0.00
3    Price Per Unit  object        0         0.00
4       Total Spent  object        0         0.00
5    Payment Method  object        0         0.00
6          Location  object        0         0.00

In [52]:
df_copy['Quantity'] = df_copy['Quantity'].astype('float')

In [53]:
summary = pd.DataFrame({
    "dtype": df_copy.dtypes,
    "missing": df_copy.isnull().sum()
}).reset_index()

summary

              index    dtype  missing
0    Transaction ID   object        0
1              Item   object        0
2          Quantity  float64        0
3    Price Per Unit   object        0
4       Total Spent   object        0
5    Payment Method   object        0
6          Location   object        0
7  Transaction Date   object      159

In [54]:
df_copy['Total Spent'] = df_copy['Total Spent'].astype('float')

In [55]:
df_copy['Price Per Unit'] = df_copy['Price Per Unit'].astype('float')

In [56]:
summary = pd.DataFrame({
    "dtype": df_copy.dtypes,
    "missing": df_copy.isnull().sum()
}).reset_index()

summary

              index    dtype  missing
0    Transaction ID   object        0
1              Item   object        0
2          Quantity  float64        0
3    Price Per Unit  float64        0
4       Total Spent  float64        0
5    Payment Method   object        0
6          Location   object        0
7  Transaction Date   object      159

In [57]:
df_copy['Price Per Unit'] = df_copy['Price Per Unit'].fillna(df_copy['Total Spent'] / df_copy['Quantity'])

In [58]:
df_copy['Quantity'] = df_copy['Quantity'].fillna(df_copy['Total Spent'] / df_copy['Price Per Unit'])

In [59]:
df_copy['Total Spent'] = df_copy['Quantity'].fillna(df_copy['Quantity'] * df_copy['Price Per Unit'])

In [60]:
summary = pd.DataFrame({
    "dtype": df_copy.dtypes,
    "missing": df_copy.isnull().sum()
}).reset_index()

summary

              index    dtype  missing
0    Transaction ID   object        0
1              Item   object        0
2          Quantity  float64        0
3    Price Per Unit  float64        0
4       Total Spent  float64        0
5    Payment Method   object        0
6          Location   object        0
7  Transaction Date   object      159

In [61]:
df_copy['Transaction Date'] = df_copy['Transaction Date'].fillna('No Date')

In [62]:
df_copy['Transaction Date'] = df_copy['Transaction Date'].replace('ERROR', 'No Date')

In [63]:
df_copy['Transaction Date'] = df_copy['Transaction Date'].replace('UNKNOWN', 'No Date')

In [64]:
summary = pd.DataFrame({
    "dtype": df_copy.dtypes,
    "missing": df_copy.isnull().sum()
}).reset_index()

summary

              index    dtype  missing
0    Transaction ID   object        0
1              Item   object        0
2          Quantity  float64        0
3    Price Per Unit  float64        0
4       Total Spent  float64        0
5    Payment Method   object        0
6          Location   object        0
7  Transaction Date   object        0

In [66]:
df_copy.to_csv('Cleaned_Coffee_Ugly_Data.csv')