### Exercise 1: Accessing Columns and Rows

In [1]:
import numpy as np
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 30, 35, 40, 22],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'],
    'Salary': [70000, 80000, 120000, 90000, 60000]
}
df = pd.DataFrame(data)
df.set_index('Name', inplace=True)
df

         Age         City  Salary
Name
Alice     25     New York   70000
Bob       30  Los Angeles   80000
Charlie   35      Chicago  120000
David     40      Houston   90000
Eva       22      Phoenix   60000

In [5]:
df['Salary']

Name
Alice       70000
Bob         80000
Charlie    120000
David       90000
Eva         60000
Name: Salary, dtype: int64

In [8]:
df.Salary

Name
Alice       70000
Bob         80000
Charlie    120000
David       90000
Eva         60000
Name: Salary, dtype: int64

In [9]:
df.loc['Charlie']

Age            35
City      Chicago
Salary     120000
Name: Charlie, dtype: object

In [10]:
df.iloc[2]

Age            35
City      Chicago
Salary     120000
Name: Charlie, dtype: object

### Exercise 2: Slicing

In [11]:
df.loc['Bob':'David']

         Age         City  Salary
Name
Bob       30  Los Angeles   80000
Charlie   35      Chicago  120000
David     40      Houston   90000

In [12]:
df.iloc[:3, 2:]

         Salary
Name
Alice     70000
Bob       80000
Charlie  120000

In [14]:
df.loc[('Alice', 'Eva'), ('Age', 'City')]

       Age      City
Name
Alice   25  New York
Eva     22   Phoenix

### Exercise 3: Boolean Indexing

In [16]:
m = df['Age'] > 30
df[m]

         Age     City  Salary
Name
Charlie   35  Chicago  120000
David     40  Houston   90000

In [22]:
m = ((df['City'] == 'New York') | (df['City'] == 'Chicago'))
df[m]

         Age      City  Salary
Name
Alice     25  New York   70000
Charlie   35   Chicago  120000

### Exercise 4: Adding and Removing Columns

In [78]:
df['Bonus'] = (df['Salary'] * 0.1)
df

         Age         City  Salary  Senior    Bonus
Name
Alice     25     New York   70000   False   7000.0
Bob       30  Los Angeles   80000   False   8000.0
Charlie   35      Chicago  120000    True  12000.0
David     40      Houston   90000    True   9000.0
Eva       22      Phoenix   60000   False   6000.0

In [76]:
df['Senior'] = df['Age'] >= 35
df

         Age         City  Salary  Senior    Bonus
Name
Alice     25     New York   70000   False   7000.0
Bob       30  Los Angeles   80000   False   8000.0
Charlie   35      Chicago  120000    True  12000.0
David     40      Houston   90000    True   9000.0
Eva       22      Phoenix   60000   False   6000.0

In [59]:
del df["City"]
df

         Age  Salary    Bonus  Senior
Name
Alice     25   70000   7000.0   False
Bob       30   80000   8000.0   False
Charlie   35  120000  12000.0    True
David     40   90000   9000.0    True
Eva       22   60000   6000.0   False

In [70]:
df.drop(columns='City')

         Age  Salary  Senior    Bonus
Name
Alice     25   70000   False   7000.0
Bob       30   80000   False   8000.0
Charlie   35  120000    True  12000.0
David     40   90000    True   9000.0
Eva       22   60000   False   6000.0

In [79]:
removed_bonus_columns = df.pop('Bonus')
print(removed_bonus_columns)
df

Name
Alice       7000.0
Bob         8000.0
Charlie    12000.0
David       9000.0
Eva         6000.0
Name: Bonus, dtype: float64

         Age         City  Salary  Senior
Name
Alice     25     New York   70000   False
Bob       30  Los Angeles   80000   False
Charlie   35      Chicago  120000    True
David     40      Houston   90000    True
Eva       22      Phoenix   60000   False

### Exercise 5: Using assign

In [86]:
m = df['Salary'] / 12
df.assign(Monthly_Salary = m)

         Age         City  Salary  Monthly_Salary
Name
Alice     25     New York   70000     5833.333333
Bob       30  Los Angeles   80000     6666.666667
Charlie   35      Chicago  120000    10000.000000
David     40      Houston   90000     7500.000000
Eva       22      Phoenix   60000     5000.000000

### Exercise 6: Sorting by Index and Values

In [93]:
df.sort_index(ascending=False)

         Age         City  Salary
Name
Eva       22      Phoenix   60000
David     40      Houston   90000
Charlie   35      Chicago  120000
Bob       30  Los Angeles   80000
Alice     25     New York   70000

In [94]:
df.sort_values(by='Age')

         Age         City  Salary
Name
Eva       22      Phoenix   60000
Alice     25     New York   70000
Bob       30  Los Angeles   80000
Charlie   35      Chicago  120000
David     40      Houston   90000

In [95]:
df.sort_values(by='Salary', ascending=False)

         Age         City  Salary
Name
Charlie   35      Chicago  120000
David     40      Houston   90000
Bob       30  Los Angeles   80000
Alice     25     New York   70000
Eva       22      Phoenix   60000

### Exercise 7: Arithmetic and Aggregation

In [19]:
grades = pd.DataFrame(
    np.random.randint(50, 100, size=(5, 3)),
    columns=['Math', 'Science', 'English'],
    index=['Alice', 'Bob', 'Charlie', 'David', 'Eva']
)

grades + 5

         Math  Science  English
Alice      84       55       99
Bob        89       80       71
Charlie    66       99       87
David      58       81       90
Eva        85       55       62

In [20]:
cols = ['Math', 'Science', 'English']
grades['Average Grade for each student'] = grades[cols].mean(axis=1)
grades

         Math  Science  English  Average Grade for each student
Alice      79       50       94                       74.333333
Bob        84       75       66                       75.000000
Charlie    61       94       82                       79.000000
David      53       76       85                       71.333333
Eva        80       50       57                       62.333333

In [ ]:
grades.loc['Average Grade for each subject'] = grades[cols].mean(axis=0)
grades

,Math,Science,English,Average Grade for each student
Alice,79.0,50.0,94.0,74.333333
Bob,84.0,75.0,66.0,75.000000
Charlie,61.0,94.0,82.0,79.000000
David,53.0,76.0,85.0,71.333333
Eva,80.0,50.0,57.0,62.333333
Average Grade for each subject,71.4,69.0,76.8,NaN

:

### Exercise 8: Handling Missing Data

In [ ]:
df_missing = pd.DataFrame({
    'A': [1, 2, np.nan, 4],
    'B': [5, np.nan, np.nan, 8],
    'C': [10, 11, 12, 13]
})

df_missing.isnull()

       A      B      C
0  False  False  False
1  False   True  False
2   True   True  False
3  False  False  False

In [8]:
df_missing.dropna(how='any', axis=0)

     A    B   C
0  1.0  5.0  10
3  4.0  8.0  13

In [10]:
df_missing.fillna(value=0)

     A    B   C
0  1.0  5.0  10
1  2.0  0.0  11
2  0.0  0.0  12
3  4.0  8.0  13

In [18]:
df_missing_cols = df_missing.columns
df_missing.fillna(value=df_missing[df_missing_cols].mean(axis=0, skipna=True))

          A    B   C
0  1.000000  5.0  10
1  2.000000  6.5  11
2  2.333333  6.5  12
3  4.000000  8.0  13

### Exercise 9: Handling Duplicates

In [4]:
df_dup = pd.DataFrame({
    'ID': [1, 2, 2, 3, 4, 4],
    'Value': ['A', 'B', 'B', 'C', 'D', 'D']
})

df_dup.duplicated()

0    False
1    False
2     True
3    False
4    False
5     True
dtype: bool

In [5]:
df_dup.drop_duplicates()

   ID Value
0   1     A
1   2     B
3   3     C
4   4     D

### Exercise 10: Data Type Conversion

In [25]:
df_str = pd.DataFrame({
    'Price': ['100', '200', '300', '400']
})

df_str.dtypes

Price    object
dtype: object

In [ ]:
df_int = df_str.astype(int)
df_int

   Price
0    100
1    200
2    300
3    400

In [24]:
df_int.dtypes

Price    int64
dtype: object