In [2]:
import pandas as pd

In [4]:
ages = [10, 20, 30, 40]

s1 = pd.Series(data=ages, index=['Person1', 'Person2', 'Person3', 'Person4'])
s2 = pd.Series(
    [179,  180, 170, 160],
    index=['Person1', 'Person2', 'Person3', 'Person4']
)

df = pd.DataFrame({
    'age': s1,
    'height': s2
})

df

         age  height
Person1   10     179
Person2   20     180
Person3   30     170
Person4   40     160

In [11]:
from pathlib import Path

csv_path = Path(r'C:\Users\konta\Documents\DIV_Academy\Module2(From_29_nov)\data\world_population.csv')

df = pd.read_csv(csv_path)
df

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [23]:
print(df['CCA3'])
df2 = df[[
    'CCA3', 'Country', 'Capital', 'Continent', '2022 Population', '2020 Population', '2015 Population'
    ]].copy()

df2.head(3)

0      AFG
1      ALB
2      DZA
3      ASM
4      AND
      ...
229    WLF
230    ESH
231    YEM
232    ZMB
233    ZWE
Name: CCA3, Length: 234, dtype: object

,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population
0,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0
1,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0
2,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0

In [62]:
df3 = df2.set_index(['Continent', 'CCA3']).sort_index()
df3

                         Country      Capital  2022 Population  \
Continent     CCA3
Africa        AGO         Angola       Luanda       35588987.0
              BDI        Burundi    Bujumbura       12889576.0
              BEN          Benin   Porto-Novo       13352864.0
              BFA   Burkina Faso  Ouagadougou       22673762.0
              BWA       Botswana     Gaborone        2630296.0
...                          ...          ...              ...
South America PER           Peru         Lima       34049588.0
              PRY       Paraguay     Asunción        6780744.0
              SUR       Suriname   Paramaribo         618040.0
              URY        Uruguay   Montevideo        3422794.0
              VEN      Venezuela      Caracas       28301696.0

                    2020 Population  2015 Population
Continent     CCA3
Africa        AGO        33428485.0       28127721.0
              BDI        12220227.0       10727148.0
              BEN        12643123.0       10932783.0
              BFA        21522626.0       18718019.0
              BWA         2546402.0        2305171.0
...                             ...              ...
South America PER        33304756.0       30711863.0
              PRY         6618695.0        6177950.0
              SUR          607065.0         575475.0
              URY         3429086.0        3402818.0
              VEN        28490453.0       30529716.0

[234 rows x 5 columns]

In [ ]:
df3['Country']

Continent      CCA3
Africa         AGO           Angola
               BDI          Burundi
               BEN            Benin
               BFA     Burkina Faso
               BWA         Botswana
                           ...
South America  PER             Peru
               PRY         Paraguay
               SUR         Suriname
               URY          Uruguay
               VEN        Venezuela
Name: Country, Length: 234, dtype: object

In [43]:
#df3.loc['Africa'].loc['AGO']
df3.loc[('Africa', 'AGO')]

Country                Angola
Capital                Luanda
2022 Population    35588987.0
2020 Population    33428485.0
2015 Population    28127721.0
Name: (Africa, AGO), dtype: object

In [ ]:
df3.iloc[0]

['CCA3',
 'Country',
 'Capital',
 'Continent',
 '2022 Population',
 '2020 Population',
 '2015 Population']

In [63]:
# df3.columns = [
#     ['General', 'General', 'Population', 'Population', 'Population'], 
#     ['Country', 'Capital', '2022 Population', '2020 Population', '2015 Population']
# ]
# df3
level0_cols = ['Population' if 'Population' in col else 'General' for col in df3.columns.tolist()]
level1_cols = df3.columns.tolist()
df3.columns = [
    level0_cols,  
    level1_cols
]
df3

                         General                   Population                  \
                         Country      Capital 2022 Population 2020 Population
Continent     CCA3
Africa        AGO         Angola       Luanda      35588987.0      33428485.0
              BDI        Burundi    Bujumbura      12889576.0      12220227.0
              BEN          Benin   Porto-Novo      13352864.0      12643123.0
              BFA   Burkina Faso  Ouagadougou      22673762.0      21522626.0
              BWA       Botswana     Gaborone       2630296.0       2546402.0
...                          ...          ...             ...             ...
South America PER           Peru         Lima      34049588.0      33304756.0
              PRY       Paraguay     Asunción       6780744.0       6618695.0
              SUR       Suriname   Paramaribo        618040.0        607065.0
              URY        Uruguay   Montevideo       3422794.0       3429086.0
              VEN      Venezuela      Caracas      28301696.0      28490453.0


                   2015 Population
Continent     CCA3
Africa        AGO       28127721.0
              BDI       10727148.0
              BEN       10932783.0
              BFA       18718019.0
              BWA        2305171.0
...                            ...
South America PER       30711863.0
              PRY        6177950.0
              SUR         575475.0
              URY        3402818.0
              VEN       30529716.0

[234 rows x 5 columns]

In [ ]:
df3.to_excel('World_Population.xlsx')

In [69]:
df3[('General', 'Country')]

Continent      CCA3
Africa         AGO           Angola
               BDI          Burundi
               BEN            Benin
               BFA     Burkina Faso
               BWA         Botswana
                           ...
South America  PER             Peru
               PRY         Paraguay
               SUR         Suriname
               URY          Uruguay
               VEN        Venezuela
Name: (General, Country), Length: 234, dtype: object

In [75]:
df4 = df3.droplevel(level=0) #by default -> rows

df4.droplevel(level=0, axis='columns')

,Country,Capital,2022 Population,2020 Population,2015 Population
CCA3,,,,,
AGO,Angola,Luanda,35588987.0,33428485.0,28127721.0
BDI,Burundi,Bujumbura,12889576.0,12220227.0,10727148.0
BEN,Benin,Porto-Novo,13352864.0,12643123.0,10932783.0
BFA,Burkina Faso,Ouagadougou,22673762.0,21522626.0,18718019.0
BWA,Botswana,Gaborone,2630296.0,2546402.0,2305171.0
...,...,...,...,...,...
PER,Peru,Lima,34049588.0,33304756.0,30711863.0
PRY,Paraguay,Asunción,6780744.0,6618695.0,6177950.0
SUR,Suriname,Paramaribo,618040.0,607065.0,575475.0
URY,Uruguay,Montevideo,3422794.0,3429086.0,3402818.0
VEN,Venezuela,Caracas,28301696.0,28490453.0,30529716.0

In [76]:
df4.T

CCA3                               AGO         BDI         BEN           BFA  \
General    Country              Angola     Burundi       Benin  Burkina Faso
           Capital              Luanda   Bujumbura  Porto-Novo   Ouagadougou
Population 2022 Population  35588987.0  12889576.0  13352864.0    22673762.0
           2020 Population  33428485.0  12220227.0  12643123.0    21522626.0
           2015 Population  28127721.0  10727148.0  10932783.0    18718019.0

CCA3                              BWA                       CAF           CIV  \
General    Country           Botswana  Central African Republic   Ivory Coast
           Capital           Gaborone                    Bangui  Yamoussoukro
Population 2022 Population  2630296.0                 5579144.0    28160542.0
           2020 Population  2546402.0                 5343020.0    26811790.0
           2015 Population  2305171.0                 4819333.0    23596741.0

CCA3                               CMR         COD                    COG  \
General    Country            Cameroon    DR Congo  Republic of the Congo
           Capital             Yaounde    Kinshasa            Brazzaville
Population 2022 Population  27914536.0  99010212.0              5970424.0
           2020 Population  26491087.0  92853164.0              5702174.0
           2015 Population  23012646.0  78656904.0              5064386.0

CCA3                        ...         COL         ECU               FLK  \
General    Country          ...    Colombia     Ecuador  Falkland Islands
           Capital          ...      Bogota       Quito           Stanley
Population 2022 Population  ...  51874024.0  18001000.0            3780.0
           2020 Population  ...  50930662.0  17588595.0            3747.0
           2015 Population  ...  47119728.0  16195902.0            3408.0

CCA3                                  GUF         GUY         PER        PRY  \
General    Country          French Guiana      Guyana        Peru   Paraguay
           Capital                Cayenne  Georgetown        Lima   Asunción
Population 2022 Population       304557.0    808726.0  34049588.0  6780744.0
           2020 Population       290969.0    797202.0  33304756.0  6618695.0
           2015 Population       257026.0    755031.0  30711863.0  6177950.0

CCA3                               SUR         URY         VEN
General    Country            Suriname     Uruguay   Venezuela
           Capital          Paramaribo  Montevideo     Caracas
Population 2022 Population    618040.0   3422794.0  28301696.0
           2020 Population    607065.0   3429086.0  28490453.0
           2015 Population    575475.0   3402818.0  30529716.0

[5 rows x 234 columns]

In [77]:
df4.rename({'Capital': 'Capitals'}, axis='columns')

           General                   Population                  \
           Country     Capitals 2022 Population 2020 Population
CCA3
AGO         Angola       Luanda      35588987.0      33428485.0
BDI        Burundi    Bujumbura      12889576.0      12220227.0
BEN          Benin   Porto-Novo      13352864.0      12643123.0
BFA   Burkina Faso  Ouagadougou      22673762.0      21522626.0
BWA       Botswana     Gaborone       2630296.0       2546402.0
...            ...          ...             ...             ...
PER           Peru         Lima      34049588.0      33304756.0
PRY       Paraguay     Asunción       6780744.0       6618695.0
SUR       Suriname   Paramaribo        618040.0        607065.0
URY        Uruguay   Montevideo       3422794.0       3429086.0
VEN      Venezuela      Caracas      28301696.0      28490453.0


     2015 Population
CCA3
AGO       28127721.0
BDI       10727148.0
BEN       10932783.0
BFA       18718019.0
BWA        2305171.0
...              ...
PER       30711863.0
PRY        6177950.0
SUR         575475.0
URY        3402818.0
VEN       30529716.0

[234 rows x 5 columns]

In [86]:
# df4.set_index('General')
# df4
df4.reset_index(drop=True)

          General                   Population
          Country      Capital 2022 Population 2020 Population 2015 Population
0          Angola       Luanda      35588987.0      33428485.0      28127721.0
1         Burundi    Bujumbura      12889576.0      12220227.0      10727148.0
2           Benin   Porto-Novo      13352864.0      12643123.0      10932783.0
3    Burkina Faso  Ouagadougou      22673762.0      21522626.0      18718019.0
4        Botswana     Gaborone       2630296.0       2546402.0       2305171.0
..            ...          ...             ...             ...             ...
229          Peru         Lima      34049588.0      33304756.0      30711863.0
230      Paraguay     Asunción       6780744.0       6618695.0       6177950.0
231      Suriname   Paramaribo        618040.0        607065.0        575475.0
232       Uruguay   Montevideo       3422794.0       3429086.0       3402818.0
233     Venezuela      Caracas      28301696.0      28490453.0      30529716.0

[234 rows x 5 columns]

In [85]:
df4.reset_index()

    CCA3       General                   Population                  \
               Country      Capital 2022 Population 2020 Population
0    AGO        Angola       Luanda      35588987.0      33428485.0
1    BDI       Burundi    Bujumbura      12889576.0      12220227.0
2    BEN         Benin   Porto-Novo      13352864.0      12643123.0
3    BFA  Burkina Faso  Ouagadougou      22673762.0      21522626.0
4    BWA      Botswana     Gaborone       2630296.0       2546402.0
..   ...           ...          ...             ...             ...
229  PER          Peru         Lima      34049588.0      33304756.0
230  PRY      Paraguay     Asunción       6780744.0       6618695.0
231  SUR      Suriname   Paramaribo        618040.0        607065.0
232  URY       Uruguay   Montevideo       3422794.0       3429086.0
233  VEN     Venezuela      Caracas      28301696.0      28490453.0


    2015 Population
0        28127721.0
1        10727148.0
2        10932783.0
3        18718019.0
4         2305171.0
..              ...
229      30711863.0
230       6177950.0
231        575475.0
232       3402818.0
233      30529716.0

[234 rows x 6 columns]

In [87]:
%pip install sqlalchemy psycopg2-binary

Collecting sqlalchemy
  Downloading sqlalchemy-2.0.45-cp311-cp311-win_amd64.whl.metadata (9.8 kB)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp311-cp311-win_amd64.whl.metadata (5.1 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.3.0-cp311-cp311-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\konta\anaconda3\envs\ds\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading sqlalchemy-2.0.45-cp311-cp311-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   --------- ------------------------------ 0.5/2.1 MB 2.8 MB/s eta 0:00:01
   ---------------------------------- ----- 1.8/2.1 MB 4.0 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 4.3 MB/s  0:00:00
Downloading psycopg2_binary-2.9.11-cp311-cp311-win_amd64.whl (2.7 MB)
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   --------------- ------------------------ 1.0/2.7 MB 6.3 MB/s eta 0:00:01
   ------------------------------ --------- 2.1/2.7 MB 6.5 MB/s eta 0:00:01
   ---------------------------------------- 2.7/2.7 MB 6.3 MB/s  0:00:00
Downloading greenlet-3.3.0-cp311-cp311-win_amd64.whl (301 kB)
Installing collected packages: psycopg2-binary, greenlet, sqlalchemy

   ------------- -------------------------- 1/3 [greenlet]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   ---------------------------------------- 3/3 [sqlalchemy]

Successfully installed greenlet-3.3.0 psycopg2-binary-2.9.11 sqlalchemy-2.0.45
Note: you may need to restart the kernel to use updated packages.

In [6]:
from sqlalchemy import create_engine, inspect
import pandas as pd

In [ ]:
username = 'divread'
password = 'div123'
host = '65.109.6.168'
database = 'world'

engine = create_engine(f'postgresql://{username}:{password}@{host}/{database}')
engine

Engine(postgresql://divread:***@65.109.6.168/world)

In [4]:
table_name = 'country'

df_table = pd.read_sql_table(table_name, con=engine)
df_table

,code,name,continent,region,surfacearea,indepyear,population,lifeexpectancy,gnp,gnpold,localname,governmentform,headofstate,capital,code2
0,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
1,NLD,Netherlands,Europe,Western Europe,41526.0,1581.0,15864000,78.3,371362.0,360478.0,Nederland,Constitutional Monarchy,Beatrix,5.0,NL
2,ANT,Netherlands Antilles,North America,Caribbean,800.0,NaN,217000,74.7,1941.0,NaN,Nederlandse Antillen,Nonmetropolitan Territory of The Netherlands,Beatrix,33.0,AN
3,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqipëria,Republic,Rexhep Mejdani,34.0,AL
4,DZA,Algeria,Africa,Northern Africa,2381741.0,1962.0,31471000,69.7,49982.0,46966.0,Al-Jazair/Algérie,Republic,Abdelaziz Bouteflika,35.0,DZ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,IOT,British Indian Ocean Territory,Africa,Eastern Africa,78.0,NaN,0,NaN,0.0,NaN,British Indian Ocean Territory,Dependent Territory of the UK,Elisabeth II,NaN,IO
235,SGS,South Georgia and the South Sandwich Islands,Antarctica,Antarctica,3903.0,NaN,0,NaN,0.0,NaN,South Georgia and the South Sandwich Islands,Dependent Territory of the UK,Elisabeth II,NaN,GS
236,HMD,Heard Island and McDonald Islands,Antarctica,Antarctica,359.0,NaN,0,NaN,0.0,NaN,Heard and McDonald Islands,Territory of Australia,Elisabeth II,NaN,HM
237,ATF,French Southern territories,Antarctica,Antarctica,7780.0,NaN,0,NaN,0.0,NaN,Terres australes françaises,Nonmetropolitan Territory of France,Jacques Chirac,NaN,TF
238,UMI,United States Minor Outlying Islands,Oceania,Micronesia/Caribbean,16.0,NaN,0,NaN,0.0,NaN,United States Minor Outlying Islands,Dependent Territory of the US,George W. Bush,NaN,UM

In [7]:
inspector = inspect(engine)

tables = inspector.get_table_names()

for table in tables:
    print(table)

city
country
countrylanguage

In [8]:
table_name = 'city'

df_table_city = pd.read_sql_table(table_name, con=engine)
df_table_city

        id            name countrycode       district  population
0        1           Kabul         AFG          Kabol     1780000
1        2        Qandahar         AFG       Qandahar      237500
2        3           Herat         AFG          Herat      186800
3        4  Mazar-e-Sharif         AFG          Balkh      127800
4        5       Amsterdam         NLD  Noord-Holland      731200
...    ...             ...         ...            ...         ...
4074  4075      Khan Yunis         PSE     Khan Yunis      123175
4075  4076          Hebron         PSE         Hebron      119401
4076  4077        Jabaliya         PSE     North Gaza      113901
4077  4078          Nablus         PSE         Nablus      100231
4078  4079           Rafah         PSE          Rafah       92020

[4079 rows x 5 columns]

In [9]:
table_name = 'countrylanguage'

df_table_cclanguange = pd.read_sql_table(table_name, con=engine)
df_table_cclanguange

    countrycode          language  isofficial  percentage
0           AFG            Pashto        True        52.4
1           NLD             Dutch        True        95.6
2           ANT        Papiamento        True        86.2
3           ALB         Albaniana        True        97.9
4           DZA            Arabic        True        86.0
..          ...               ...         ...         ...
979         IND             Asami       False         1.5
980         CAN  Eskimo Languages       False         0.1
981         CHN              Dong       False         0.2
982         RUS       Belorussian       False         0.3
983         USA        Portuguese       False         0.2

[984 rows x 4 columns]

In [11]:
df_table_cclanguange['countrycode']
df_table_cclanguange[df_table_cclanguange['percentage'] > 50]

    countrycode    language  isofficial  percentage
0           AFG      Pashto        True        52.4
1           NLD       Dutch        True        95.6
2           ANT  Papiamento        True        86.2
3           ALB   Albaniana        True        97.9
4           DZA      Arabic        True        86.0
..          ...         ...         ...         ...
227         EST    Estonian        True        65.3
228         USA     English        True        86.2
229         VIR     English        True        81.7
231         ZWE       Shona       False        72.1
232         PSE      Arabic       False        95.9

[168 rows x 4 columns]

In [12]:
df_table_cclanguange.groupby('language')[['percentage']].mean()

              percentage
language
Abhyasi         1.700000
Acholi          4.400000
Adja           11.100000
Afar           19.550000
Afrikaans      11.900000
...                  ...
Zapotec         0.600000
Zenaga          1.200000
Zhuang          1.400000
Zulu           13.233333
[South]Mande    7.700000

[457 rows x 1 columns]

In [13]:
df_table_cclanguange.value_counts()

countrycode  language    isofficial  percentage
ABW          Dutch       True        5.3           1
             English     False       9.5           1
             Papiamento  False       76.7          1
             Spanish     False       7.4           1
AFG          Balochi     False       0.9           1
                                                  ..
ZMB          Tongan      False       11.0          1
ZWE          English     True        2.2           1
             Ndebele     False       16.2          1
             Nyanja      False       2.2           1
             Shona       False       72.1          1
Name: count, Length: 984, dtype: int64

In [14]:
df_table_cclanguange.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 984 entries, 0 to 983
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   countrycode  984 non-null    object
 1   language     984 non-null    object
 2   isofficial   984 non-null    bool
 3   percentage   984 non-null    float64
dtypes: bool(1), float64(1), object(2)
memory usage: 24.2+ KB

In [19]:
df_table_cclanguange.sort_values(by='percentage').head(100)

    countrycode          language  isofficial  percentage
35          CYM           English        True         0.0
30          VGB           English        True         0.0
372         OMN           Balochi       False         0.0
579         TUV           English        True         0.0
383         QAT              Urdu       False         0.0
..          ...               ...         ...         ...
626         HND           Miskito       False         0.2
718         BRA  Indian Languages       False         0.2
917         AUT          Romanian       False         0.2
703         HUN    Serbo-Croatian       False         0.2
882         ITA           Slovene       False         0.2

[100 rows x 4 columns]

In [ ]:
df_table_cclanguange['is']

In [20]:
df_table_cclanguange.describe()

       percentage
count  984.000000
mean    20.374390
std     30.829452
min      0.000000
25%      1.275000
50%      5.300000
75%     21.125000
max    100.000000

### 13_Dec

In [2]:
csv_path_str = r'C:\Users\konta\Documents\DIV_Academy\Module2(From_29_nov)\data\world_population.csv'

from pathlib import Path
import pandas as pd

csv_path = Path(csv_path_str)
df = pd.read_csv(csv_path)
df.head(5)

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00

In [3]:
df.index

RangeIndex(start=0, stop=234, step=1)

In [4]:
df.values

array([[36, 'AFG', 'Afghanistan', ..., 63.0587, 1.0257, 0.52],
       [138, 'ALB', 'Albania', ..., 98.8702, 0.9957, 0.04],
       [34, 'DZA', 'Algeria', ..., 18.8531, 1.0164, 0.56],
       ...,
       [46, 'YEM', 'Yemen', ..., 63.8232, 1.0217, 0.42],
       [63, 'ZMB', 'Zambia', ..., 26.5976, 1.028, 0.25],
       [74, 'ZWE', 'Zimbabwe', ..., 41.7665, 1.0204, 0.2]],
      shape=(234, 17), dtype=object)

In [10]:
#df['Rank']
#df.Rank
#df.loc[:, 'Rank']
df.iloc[:, 0]

0       36
1      138
2       34
3      213
4      203
      ...
229    226
230    172
231     46
232     63
233     74
Name: Rank, Length: 234, dtype: int64

In [13]:
df.loc[:, 'Country': '2022 Population']
df.iloc[:, 2: 6]

               Country           Capital Continent  2022 Population
0          Afghanistan             Kabul      Asia       41128771.0
1              Albania            Tirana    Europe        2842321.0
2              Algeria           Algiers    Africa       44903225.0
3       American Samoa         Pago Pago   Oceania          44273.0
4              Andorra  Andorra la Vella    Europe          79824.0
..                 ...               ...       ...              ...
229  Wallis and Futuna          Mata-Utu   Oceania          11572.0
230     Western Sahara          El Aaiún    Africa         575986.0
231              Yemen             Sanaa      Asia       33696614.0
232             Zambia            Lusaka    Africa       20017675.0
233           Zimbabwe            Harare    Africa       16320537.0

[234 rows x 4 columns]

In [3]:
df2 = df.set_index('CCA3')
df2.head()

,Rank,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
CCA3,,,,,,,,,,,,,,,,
AFG,36,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
ALB,138,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
DZA,34,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
ASM,213,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
AND,203,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00

In [ ]:
#df2.iloc[0]
#df2.loc['AFG']

#df2.iloc[0, str(df2).index('AZE')] ???????????????????????????????

ValueError: substring not found

In [26]:
s_2025 = df2.loc[:, '2022 Population'] * 1.2
s_2025

CCA3
AFG    49354525.2
ALB     3410785.2
DZA    53883870.0
ASM       53127.6
AND       95788.8
          ...
WLF       13886.4
ESH      691183.2
YEM    40435936.8
ZMB    24021210.0
ZWE    19584644.4
Name: 2022 Population, Length: 234, dtype: float64

In [27]:
df2['2025 Population'] = s_2025
df2

,Rank,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage,2025 Population
CCA3,,,,,,,,,,,,,,,,,
AFG,36,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52,49354525.2
ALB,138,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04,3410785.2
DZA,34,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56,53883870.0
ASM,213,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00,53127.6
AND,203,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00,95788.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WLF,226,Wallis and Futuna,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00,13886.4
ESH,172,Western Sahara,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01,691183.2
YEM,46,Yemen,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42,40435936.8
ZMB,63,Zambia,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25,24021210.0
ZWE,74,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20,19584644.4

In [32]:
growth_rate_2025 = df2['Growth Rate'] * 0.8
growth_rate_2025

CCA3
AFG    0.656448
ALB    0.637248
DZA    0.650496
ASM    0.629184
AND    0.646400
         ...
WLF    0.636992
ESH    0.651776
YEM    0.653888
ZMB    0.657920
ZWE    0.653056
Name: Growth Rate, Length: 234, dtype: float64

In [33]:
df2['Growth Rate 2025'] = growth_rate_2025
df2

,Rank,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage,2025 Population,Growth Rate 2025
CCA3,,,,,,,,,,,,,,,,,,
AFG,36,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,0.82056,0.52,49354525.2,0.656448
ALB,138,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.79656,0.04,3410785.2,0.637248
DZA,34,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,0.81312,0.56,53883870.0,0.650496
ASM,213,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.78648,0.00,53127.6,0.629184
AND,203,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,0.80800,0.00,95788.8,0.646400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WLF,226,Wallis and Futuna,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.79624,0.00,13886.4,0.636992
ESH,172,Western Sahara,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,0.81472,0.01,691183.2,0.651776
YEM,46,Yemen,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,0.81736,0.42,40435936.8,0.653888
ZMB,63,Zambia,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,0.82240,0.25,24021210.0,0.657920
ZWE,74,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,0.81632,0.20,19584644.4,0.653056

In [39]:
df2.sort_index(axis=1, ascending=False).head()

,World Population Percentage,Rank,Growth Rate 2025,Growth Rate,Density (per km²),Country,Continent,Capital,Area (km²),2025 Population,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population
CCA3,,,,,,,,,,,,,,,,,,
AFG,0.52,36,0.656448,0.82056,63.0587,Afghanistan,Asia,Kabul,652230.0,49354525.2,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0
ALB,0.04,138,0.637248,0.79656,98.8702,Albania,Europe,Tirana,28748.0,3410785.2,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0
DZA,0.56,34,0.650496,0.81312,18.8531,Algeria,Africa,Algiers,2381741.0,53883870.0,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0
ASM,0.00,213,0.629184,0.78648,222.4774,American Samoa,Oceania,Pago Pago,199.0,53127.6,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0
AND,0.00,203,0.646400,0.80800,170.5641,Andorra,Europe,Andorra la Vella,468.0,95788.8,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0

In [41]:
m1 = df2.loc[:, '2022 Population'] > 50e6
m2 = df2.loc[:, 'Continent'] == 'Asia'
df2.loc[m1&m2, :]

,Rank,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage,2025 Population,Growth Rate 2025
CCA3,,,,,,,,,,,,,,,,,,
BGD,8,Bangladesh,Dhaka,Asia,1.711864e+08,1.674210e+08,1.578300e+08,1.483911e+08,1.291933e+08,1.071477e+08,83929765.0,67541860.0,147570.0,1160.0350,0.80864,2.15,2.054236e+08,0.646912
CHN,1,China,Beijing,Asia,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,982372466.0,822534450.0,9706961.0,146.8933,0.80000,17.88,1.711065e+09,0.640000
IND,2,India,New Delhi,Asia,1.417173e+09,1.396387e+09,1.322867e+09,1.240614e+09,1.059634e+09,NaN,NaN,557501301.0,3287590.0,431.0675,0.80544,17.77,1.700608e+09,0.644352
IDN,4,Indonesia,Jakarta,Asia,2.755013e+08,2.718580e+08,2.590920e+08,2.440162e+08,2.140724e+08,1.821599e+08,148177096.0,115228394.0,1904569.0,144.6529,0.80512,3.45,3.306016e+08,0.644096
IRN,17,Iran,Tehran,Asia,8.855057e+07,8.729019e+07,8.179084e+07,7.537386e+07,6.554438e+07,5.579363e+07,38520664.0,28449705.0,1648195.0,53.7258,0.80568,1.11,1.062607e+08,0.644544
JPN,11,Japan,Tokyo,Asia,1.239517e+08,1.252448e+08,1.272509e+08,1.281054e+08,1.268039e+08,1.236863e+08,117624196.0,105416839.0,377930.0,327.9753,0.79576,1.55,1.487420e+08,0.636608
MMR,26,Myanmar,Nay Pyi Taw,Asia,5.417931e+07,5.342320e+07,5.148395e+07,4.939099e+07,4.553833e+07,4.009955e+07,33465781.0,27284112.0,676578.0,80.0784,0.80568,0.68,6.501517e+07,0.644544
PAK,5,Pakistan,Islamabad,Asia,2.358249e+08,2.271967e+08,2.109693e+08,1.944545e+08,1.543699e+08,1.154141e+08,80624057.0,59290872.0,881912.0,267.4018,0.81528,2.96,2.829898e+08,0.652224
PHL,13,Philippines,Manila,Asia,1.155590e+08,1.121910e+08,1.030314e+08,9.463670e+07,7.795822e+07,6.155890e+07,48419546.0,37435586.0,342353.0,337.5434,0.81176,1.45,1.386708e+08,0.649408
KOR,29,South Korea,Seoul,Asia,5.181581e+07,5.184469e+07,5.099440e+07,4.881304e+07,4.678859e+07,4.412004e+07,38170501.0,32601143.0,100210.0,517.0722,0.79976,0.65,6.217897e+07,0.639808
THA,20,Thailand,Bangkok,Asia,7.169703e+07,7.147566e+07,7.029440e+07,6.827049e+07,6.306660e+07,5.522841e+07,45737753.0,NaN,513120.0,139.7276,0.80104,0.90,8.603644e+07,0.640832
TUR,18,Turkey,Ankara,Asia,8.534124e+07,8.413543e+07,7.964618e+07,7.319534e+07,6.411355e+07,5.432414e+07,44089069.0,35540990.0,783562.0,108.9145,0.80536,1.07,1.024095e+08,0.644288
VNM,16,Vietnam,Hanoi,Asia,9.818686e+07,9.664868e+07,9.219140e+07,8.741101e+07,7.900114e+07,6.691261e+07,52968270.0,41928849.0,331212.0,296.4472,0.80592,1.23,1.178242e+08,0.644736

In [5]:
df3 = df2.select_dtypes(include='float64')
m2d = df3 > 50e6
df3[m2d].dropna(how='all')

,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
CCA3,,,,,,,,,,,,
BGD,1.711864e+08,1.674210e+08,1.578300e+08,1.483911e+08,1.291933e+08,1.071477e+08,83929765.0,67541860.0,NaN,NaN,NaN,NaN
BRA,2.153135e+08,2.131963e+08,2.051882e+08,1.963535e+08,1.758737e+08,1.507064e+08,122288383.0,96369875.0,NaN,NaN,NaN,NaN
CHN,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,982372466.0,822534450.0,NaN,NaN,NaN,NaN
COL,5.187402e+07,5.093066e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
COD,9.901021e+07,9.285316e+07,7.865690e+07,6.639126e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
EGY,1.109901e+08,1.074651e+08,9.772380e+07,8.725241e+07,7.137137e+07,5.721463e+07,NaN,NaN,NaN,NaN,NaN,NaN
ETH,1.233799e+08,1.171909e+08,1.024719e+08,8.923779e+07,6.703187e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FRA,6.462663e+07,6.448005e+07,6.380977e+07,6.244457e+07,5.866545e+07,5.641290e+07,53713830.0,50523586.0,NaN,NaN,NaN,NaN
DEU,8.336984e+07,8.332899e+07,8.207323e+07,8.132509e+07,8.155168e+07,7.937020e+07,77786703.0,78294583.0,NaN,NaN,NaN,NaN
IND,1.417173e+09,1.396387e+09,1.322867e+09,1.240614e+09,1.059634e+09,NaN,NaN,557501301.0,NaN,NaN,NaN,NaN
IDN,2.755013e+08,2.718580e+08,2.590920e+08,2.440162e+08,2.140724e+08,1.821599e+08,148177096.0,115228394.0,NaN,NaN,NaN,NaN
IRN,8.855057e+07,8.729019e+07,8.179084e+07,7.537386e+07,6.554438e+07,5.579363e+07,NaN,NaN,NaN,NaN,NaN,NaN
ITA,5.903747e+07,5.950058e+07,6.023291e+07,5.982245e+07,5.696640e+07,5.675656e+07,56329482.0,53324036.0,NaN,NaN,NaN,NaN
JPN,1.239517e+08,1.252448e+08,1.272509e+08,1.281054e+08,1.268039e+08,1.236863e+08,117624196.0,105416839.0,NaN,NaN,NaN,NaN
KEN,5.402749e+07,5.198578e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MEX,1.275041e+08,1.259983e+08,1.201499e+08,1.125324e+08,9.787344e+07,8.172043e+07,67705186.0,50289306.0,NaN,NaN,NaN,NaN
MMR,5.417931e+07,5.342320e+07,5.148395e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NGA,2.185412e+08,2.083274e+08,1.839958e+08,1.609529e+08,1.228520e+08,9.521426e+07,72951439.0,55569264.0,NaN,NaN,NaN,NaN
PAK,2.358249e+08,2.271967e+08,2.109693e+08,1.944545e+08,1.543699e+08,1.154141e+08,80624057.0,59290872.0,NaN,NaN,NaN,NaN
PHL,1.155590e+08,1.121910e+08,1.030314e+08,9.463670e+07,7.795822e+07,6.155890e+07,NaN,NaN,NaN,NaN,NaN,NaN
RUS,1.447133e+08,1.456173e+08,1.446684e+08,1.432426e+08,1.468448e+08,1.480057e+08,138257420.0,130093010.0,NaN,NaN,NaN,NaN
ZAF,5.989388e+07,5.880193e+07,5.587650e+07,5.178492e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
KOR,5.181581e+07,5.184469e+07,5.099440e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TZA,6.549775e+07,6.170452e+07,5.254282e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
THA,7.169703e+07,7.147566e+07,7.029440e+07,6.827049e+07,6.306660e+07,5.522841e+07,NaN,NaN,NaN,NaN,NaN,NaN
TUR,8.534124e+07,8.413543e+07,7.964618e+07,7.319534e+07,6.411355e+07,5.432414e+07,NaN,NaN,NaN,NaN,NaN,NaN
UKR,NaN,NaN,NaN,NaN,NaN,5.158982e+07,NaN,NaN,NaN,NaN,NaN,NaN
GBR,6.750894e+07,6.705947e+07,6.522436e+07,6.276004e+07,5.885004e+07,5.721044e+07,56326328.0,55650166.0,NaN,NaN,NaN,NaN
USA,3.382899e+08,3.359420e+08,3.246078e+08,3.111828e+08,2.823986e+08,2.480837e+08,223140018.0,200328340.0,NaN,NaN,NaN,NaN
VNM,9.818686e+07,9.664868e+07,9.219140e+07,8.741101e+07,7.900114e+07,6.691261e+07,52968270.0,NaN,NaN,NaN,NaN,NaN