### Exercise 1: Concatenating DataFrames

In [2]:
import pandas as pd

df1 = pd.DataFrame({'A': ['A0', 'A1'], 'B': ['B0', 'B1']}, index=[0, 1])
df2 = pd.DataFrame({'A': ['A2', 'A3'], 'B': ['B2', 'B3']}, index=[2, 3])

concat_vert = pd.concat([df1, df2], axis=0)
concat_vert

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

In [9]:
concat_horz = pd.concat([df1, df2], axis=1)
concat_horz

     A    B    A    B
0   A0   B0  NaN  NaN
1   A1   B1  NaN  NaN
2  NaN  NaN   A2   B2
3  NaN  NaN   A3   B3

In [15]:
df3 = pd.DataFrame({'A': ['A4', 'A5'], 'B': ['B4', 'B5']}, index=[0, 1])
concat_df1_df3_vertic = pd.concat([df1, df3], axis=0, ignore_index=True)
concat_df1_df3_vertic

    A   B
0  A0  B0
1  A1  B1
2  A4  B4
3  A5  B5

### Exercise 2: Merging DataFrames (Inner, Outer, Left, Right)

In [ ]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2'], 'A': ['A0', 'A1', 'A2']})
right = pd.DataFrame({'key': ['K0', 'K1', 'K3'], 'B': ['B0', 'B1', 'B3']})

inner_merge = pd.merge(left=left, right=right, how='inner', on='key')
inner_merge

  key   A   B
0  K0  A0  B0
1  K1  A1  B1

In [19]:
outer_merge = pd.merge(left, right, how='outer', on='key')
outer_merge

  key    A    B
0  K0   A0   B0
1  K1   A1   B1
2  K2   A2  NaN
3  K3  NaN   B3

In [20]:
left_merge = pd.merge(left, right, how='left', on='key')
left_merge

  key   A    B
0  K0  A0   B0
1  K1  A1   B1
2  K2  A2  NaN

In [21]:
right_merge = pd.merge(left, right, how='right', on='key')
right_merge

  key    A   B
0  K0   A0  B0
1  K1   A1  B1
2  K3  NaN  B3

### Exercise 3: Merging on Different Keys

In [24]:
df_employees = pd.DataFrame({'emp_id': [1, 2, 3, 4], 'name': ['Alice', 'Bob', 'Charlie', 'David']})
df_salaries = pd.DataFrame({'id': [1, 2, 3, 5], 'salary': [50000, 60000, 70000, 80000]})

result = pd.merge(df_employees, df_salaries, left_on='emp_id', right_on='id')

result

   emp_id     name  id  salary
0       1    Alice   1   50000
1       2      Bob   2   60000
2       3  Charlie   3   70000

In [26]:
result.drop('id', axis=1)

   emp_id     name  salary
0       1    Alice   50000
1       2      Bob   60000
2       3  Charlie   70000

### Exercise 4: GroupBy and Simple Aggregation

In [2]:
import seaborn as sns
planets = sns.load_dataset('planets')

planets.head()

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [10]:
planets.groupby(by='method').count()

                               number  orbital_period  mass  distance  year
method
Astrometry                          2               2     0         2     2
Eclipse Timing Variations           9               9     2         4     9
Imaging                            38              12     0        32    38
Microlensing                       23               7     0        10    23
Orbital Brightness Modulation       3               3     0         2     3
Pulsar Timing                       5               5     0         1     5
Pulsation Timing Variations         1               1     0         0     1
Radial Velocity                   553             553   510       530   553
Transit                           397             397     1       224   397
Transit Timing Variations           4               3     0         3     4

In [12]:
planets.groupby(by='method')['orbital_period'].mean()

method
Astrometry                          631.180000
Eclipse Timing Variations          4751.644444
Imaging                          118247.737500
Microlensing                       3153.571429
Orbital Brightness Modulation         0.709307
Pulsar Timing                      7343.021201
Pulsation Timing Variations        1170.000000
Radial Velocity                     823.354680
Transit                              21.102073
Transit Timing Variations            79.783500
Name: orbital_period, dtype: float64

### Exercise 5: GroupBy with Multiple Aggregations

In [13]:
planets.groupby('method').min()

                               number  orbital_period    mass  distance  year
method
Astrometry                          1      246.360000     NaN     14.98  2010
Eclipse Timing Variations           1     1916.250000  4.2000    130.72  2008
Imaging                             1     4639.150000     NaN      7.69  2004
Microlensing                        1     1825.000000     NaN   1760.00  2004
Orbital Brightness Modulation       1        0.240104     NaN   1180.00  2011
Pulsar Timing                       1        0.090706     NaN   1200.00  1992
Pulsation Timing Variations         1     1170.000000     NaN       NaN  2007
Radial Velocity                     1        0.736540  0.0036      1.35  1989
Transit                             1        0.355000  1.4700     38.00  2002
Transit Timing Variations           2       22.339500     NaN    339.00  2011

In [14]:
planets.groupby('method').median()

                               number  orbital_period   mass  distance    year
method
Astrometry                        1.0      631.180000    NaN    17.875  2011.5
Eclipse Timing Variations         2.0     4343.500000  5.125   315.360  2010.0
Imaging                           1.0    27500.000000    NaN    40.395  2009.0
Microlensing                      1.0     3300.000000    NaN  3840.000  2010.0
Orbital Brightness Modulation     2.0        0.342887    NaN  1180.000  2011.0
Pulsar Timing                     3.0       66.541900    NaN  1200.000  1994.0
Pulsation Timing Variations       1.0     1170.000000    NaN       NaN  2007.0
Radial Velocity                   1.0      360.200000  1.260    40.445  2009.0
Transit                           1.0        5.714932  1.470   341.000  2012.0
Transit Timing Variations         2.0       57.011000    NaN   855.000  2012.5

In [15]:
planets.groupby('method').max()

                               number  orbital_period   mass  distance  year
method
Astrometry                          1     1016.000000    NaN     20.77  2013
Eclipse Timing Variations           2    10220.000000   6.05    500.00  2012
Imaging                             4   730000.000000    NaN    165.00  2013
Microlensing                        2     5100.000000    NaN   7720.00  2013
Orbital Brightness Modulation       2        1.544929    NaN   1180.00  2013
Pulsar Timing                       3    36525.000000    NaN   1200.00  2011
Pulsation Timing Variations         1     1170.000000    NaN       NaN  2007
Radial Velocity                     6    17337.500000  25.00    354.00  2014
Transit                             7      331.600590   1.47   8500.00  2014
Transit Timing Variations           3      160.000000    NaN   2119.00  2014

In [16]:
planets.groupby('method').aggregate(['min', 'median', 'max'])

                              number            orbital_period                \
                                 min median max            min        median
method
Astrometry                         1    1.0   1     246.360000    631.180000
Eclipse Timing Variations          1    2.0   2    1916.250000   4343.500000
Imaging                            1    1.0   4    4639.150000  27500.000000
Microlensing                       1    1.0   2    1825.000000   3300.000000
Orbital Brightness Modulation      1    2.0   2       0.240104      0.342887
Pulsar Timing                      1    3.0   3       0.090706     66.541900
Pulsation Timing Variations        1    1.0   1    1170.000000   1170.000000
Radial Velocity                    1    1.0   6       0.736540    360.200000
Transit                            1    1.0   7       0.355000      5.714932
Transit Timing Variations          2    2.0   3      22.339500     57.011000

                                                mass               distance  \
                                         max     min median    max      min
method
Astrometry                       1016.000000     NaN    NaN    NaN    14.98
Eclipse Timing Variations       10220.000000  4.2000  5.125   6.05   130.72
Imaging                        730000.000000     NaN    NaN    NaN     7.69
Microlensing                     5100.000000     NaN    NaN    NaN  1760.00
Orbital Brightness Modulation       1.544929     NaN    NaN    NaN  1180.00
Pulsar Timing                   36525.000000     NaN    NaN    NaN  1200.00
Pulsation Timing Variations      1170.000000     NaN    NaN    NaN      NaN
Radial Velocity                 17337.500000  0.0036  1.260  25.00     1.35
Transit                           331.600590  1.4700  1.470   1.47    38.00
Transit Timing Variations         160.000000     NaN    NaN    NaN   339.00

                                                  year
                                 median      max   min  median   max
method
Astrometry                       17.875    20.77  2010  2011.5  2013
Eclipse Timing Variations       315.360   500.00  2008  2010.0  2012
Imaging                          40.395   165.00  2004  2009.0  2013
Microlensing                   3840.000  7720.00  2004  2010.0  2013
Orbital Brightness Modulation  1180.000  1180.00  2011  2011.0  2013
Pulsar Timing                  1200.000  1200.00  1992  1994.0  2011
Pulsation Timing Variations         NaN      NaN  2007  2007.0  2007
Radial Velocity                  40.445   354.00  1989  2009.0  2014
Transit                         341.000  8500.00  2002  2012.0  2014
Transit Timing Variations       855.000  2119.00  2011  2012.5  2014

### Exercise 6: Aggregate, Filter, Transform, Apply

In [60]:
df = pd.DataFrame({
    'Team': ['A', 'A', 'B', 'B', 'C', 'C'],
    'Points': [10, 15, 10, 20, 10, 5],
    'Assists': [5, 7, 5, 10, 5, 2]
})

grouped = df.groupby('Team')[['Points', 'Assists']].sum()
grouped

      Points  Assists
Team
A         25       12
B         30       15
C         15        7

In [61]:
team_stats = (
    df.groupby('Team')
    .agg(
        Points=('Points', 'mean'),
        Assists=('Assists', 'sum')
        )
)

team_stats[team_stats['Points'] < 12.0]

      Points  Assists
Team
C        7.5        7

In [62]:
grouped['Points_Standardized'] = grouped[['Points']] - team_stats[['Points']]
grouped

      Points  Assists  Points_Standardized
Team
A         25       12                 12.5
B         30       15                 15.0
C         15        7                  7.5

In [76]:
def doubles(x):
    if x['Assists'].sum() > 10:
        x['Points'] = x['Points'] * 2
    return x

result = grouped.groupby('Team').apply(doubles)
result = result.reset_index(level=0, drop=True)
result

      Points  Assists  Points_Standardized
Team
A         50       12                 12.5
B         60       15                 15.0
C         15        7                  7.5

### Exercise 7: Creating Pivot Tables

In [1]:
import seaborn as sns

titanic = sns.load_dataset('titanic')

In [2]:
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [4]:
titanic.pivot_table('survived', index='sex', columns='class', aggfunc='mean')

C:\Users\konta\AppData\Local\Temp\ipykernel_8748\619644514.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  titanic.pivot_table('survived', index='sex', columns='class', aggfunc='mean')

class      First    Second     Third
sex
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [9]:
titanic.pivot_table('survived', index='sex', columns='class', margins = True,aggfunc='mean')

C:\Users\konta\AppData\Local\Temp\ipykernel_8748\3970881083.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  titanic.pivot_table('survived', index='sex', columns='class', margins = True,aggfunc='mean')

class      First    Second     Third       All
sex
female  0.968085  0.921053  0.500000  0.742038
male    0.368852  0.157407  0.135447  0.188908
All     0.629630  0.472826  0.242363  0.383838

### Exercise 8: Advanced Pivot Tables

In [12]:
titanic.pivot_table(index='sex', columns='class', aggfunc={'survived':sum, 'fare': 'mean'})

C:\Users\konta\AppData\Local\Temp\ipykernel_8748\1016281713.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  titanic.pivot_table(index='sex', columns='class', aggfunc={'survived':sum, 'fare': 'mean'})
C:\Users\konta\AppData\Local\Temp\ipykernel_8748\1016281713.py:1: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  titanic.pivot_table(index='sex', columns='class', aggfunc={'survived':sum, 'fare': 'mean'})

              fare                       survived
class        First     Second      Third    First Second Third
sex
female  106.125798  21.970121  16.118810       91     70    72
male     67.226127  19.741782  12.661633       45     17    47

In [13]:
titanic.pivot_table(index=['sex', 'embarked'], columns='class', aggfunc={'survived':sum, 'fare': 'mean'})

C:\Users\konta\AppData\Local\Temp\ipykernel_8748\3586809069.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  titanic.pivot_table(index=['sex', 'embarked'], columns='class', aggfunc={'survived':sum, 'fare': 'mean'})
C:\Users\konta\AppData\Local\Temp\ipykernel_8748\3586809069.py:1: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  titanic.pivot_table(index=['sex', 'embarked'], columns='class', aggfunc={'survived':sum, 'fare': 'mean'})

                       fare                       survived
class                 First     Second      Third    First Second Third
sex    embarked
female C         115.640309  25.268457  14.694926       42      7    15
       Q          90.000000  12.350000  10.307833        1      2    24
       S          99.026910  21.912687  18.670077       46     61    33
male   C          93.536707  25.421250   9.352237       17      2    10
       Q          90.000000  12.350000  11.924251        0      0     3
       S          52.949947  19.232474  13.307149       28     15    34