### Exercise 1: Basic String Methods

In [2]:
import numpy as np
import pandas as pd

In [52]:
names = pd.Series(['Alice Smith', 'Bob Jones', 'Charlie Brown', 'David Wilson'])

In [10]:
names.str.lower().to_frame()

               0
0    alice smith
1      bob jones
2  charlie brown
3   david wilson

In [11]:
names.str.upper().to_frame()

               0
0    ALICE SMITH
1      BOB JONES
2  CHARLIE BROWN
3   DAVID WILSON

In [12]:
names.str.len().to_frame()

    0
0  11
1   9
2  13
3  12

### Exercise 2: Splitting and Slicing Strings

In [16]:
splitted = names.str.split()
splitted

0      [Alice, Smith]
1        [Bob, Jones]
2    [Charlie, Brown]
3     [David, Wilson]
dtype: object

In [56]:
Names = splitted.str[0]
Names

0      Alice
1        Bob
2    Charlie
3      David
dtype: object

In [57]:
Names.str[0:3]

0    Ali
1    Bob
2    Cha
3    Dav
dtype: object

### Exercise 3: String Filtering

In [55]:
names.loc[names.str.startswith('C')]

2    Charlie Brown
dtype: object

In [54]:
names.loc[names.str.contains('Jones')]

1    Bob Jones
dtype: object

### Exercise 4: Creating and Formatting Dates

In [58]:
from datetime import datetime

In [64]:
date = datetime(year=2023, month=1, day=1)

In [74]:
string_date = date.strftime('%d-%B-%Y')
string_date

'01-January-2023'

In [75]:
pd.to_datetime(string_date)

Timestamp('2023-01-01 00:00:00')

### Exercise 5: Date Arithmetic and Ranges

In [77]:
from datetime import datetime as dt 
tstamp = dt.today()
tstamp

datetime.datetime(2026, 1, 9, 22, 59, 46, 187174)

In [79]:
tstamp + pd.to_timedelta(np.arange(7), 'D')

DatetimeIndex(['2026-01-09 22:59:46.187174', '2026-01-10 22:59:46.187174',
               '2026-01-11 22:59:46.187174', '2026-01-12 22:59:46.187174',
               '2026-01-13 22:59:46.187174', '2026-01-14 22:59:46.187174',
               '2026-01-15 22:59:46.187174'],
              dtype='datetime64[ns]', freq=None)

In [82]:
pd.date_range('January 1, 2023', 'January 10, 2023')

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10'],
              dtype='datetime64[ns]', freq='D')

In [83]:
pd.date_range('January 2023', periods=5)

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05'],
              dtype='datetime64[ns]', freq='D')

### Exercise 6: Indexing by Time

In [3]:
dates = pd.date_range('2023-01-01', periods=6, freq='D')
data = pd.Series([10, 12, 15, 14, 18, 20], index=dates)

In [4]:
data

2023-01-01    10
2023-01-02    12
2023-01-03    15
2023-01-04    14
2023-01-05    18
2023-01-06    20
Freq: D, dtype: int64

In [5]:
data.loc['2023-01-03']

np.int64(15)

In [6]:
data.loc['2023-01-02':'2023-01-05']

2023-01-02    12
2023-01-03    15
2023-01-04    14
2023-01-05    18
Freq: D, dtype: int64

### Exercise 7: Resampling

In [7]:
dates = pd.date_range('2023-01-01', periods=100, freq='D')
df = pd.DataFrame({'Value': np.random.randn(100)}, index=dates)

In [8]:
df

               Value
2023-01-01 -1.447566
2023-01-02 -0.810070
2023-01-03  0.884956
2023-01-04  2.245153
2023-01-05 -1.564599
...              ...
2023-04-06  1.008703
2023-04-07 -1.572416
2023-04-08  0.503702
2023-04-09 -0.336784
2023-04-10  0.041149

[100 rows x 1 columns]

In [12]:
df.resample('ME').mean()

               Value
2023-01-31 -0.223859
2023-02-28  0.152675
2023-03-31 -0.352195
2023-04-30 -0.525813

In [13]:
df.resample('W').sum()

               Value
2023-01-01 -1.447566
2023-01-08 -1.354691
2023-01-15  1.362164
2023-01-22 -1.704769
2023-01-29 -3.434899
2023-02-05 -3.923840
2023-02-12 -0.439791
2023-02-19  2.244695
2023-02-26  3.955516
2023-03-05  2.183949
2023-03-12 -5.136697
2023-03-19 -0.440984
2023-03-26 -3.800072
2023-04-02 -3.453188
2023-04-09 -3.491901
2023-04-16  0.041149

### Exercise 8: Shifting and Rolling Windows

In [6]:
dates = pd.date_range('2023-01-01', periods=100, freq='D')
df = pd.DataFrame({'Value': np.random.randn(100)}, index=dates)

In [13]:
df['Shifted_Value'] = df['Value'].shift(1)

In [14]:
df

               Value  Shifted_Value
2023-01-01  1.041766            NaN
2023-01-02 -0.360048       1.041766
2023-01-03 -1.203967      -0.360048
2023-01-04  1.885765      -1.203967
2023-01-05  1.433257       1.885765
...              ...            ...
2023-04-06  1.177315       1.240115
2023-04-07  1.920212       1.177315
2023-04-08 -0.695323       1.920212
2023-04-09  0.341623      -0.695323
2023-04-10 -1.999998       0.341623

[100 rows x 2 columns]

In [17]:
df['Rolling_Mean'] = df['Value'].rolling(window=7).mean()

In [18]:
df

               Value  Shifted_Value  Rolling_Mean
2023-01-01  1.041766            NaN           NaN
2023-01-02 -0.360048       1.041766           NaN
2023-01-03 -1.203967      -0.360048           NaN
2023-01-04  1.885765      -1.203967           NaN
2023-01-05  1.433257       1.885765           NaN
...              ...            ...           ...
2023-04-06  1.177315       1.240115      0.708906
2023-04-07  1.920212       1.177315      0.797888
2023-04-08 -0.695323       1.920212      0.734182
2023-04-09  0.341623      -0.695323      0.891921
2023-04-10 -1.999998       0.341623      0.440821

[100 rows x 3 columns]

In [21]:
df.iloc[:10, :]

               Value  Shifted_Value  Rolling_Mean
2023-01-01  1.041766            NaN           NaN
2023-01-02 -0.360048       1.041766           NaN
2023-01-03 -1.203967      -0.360048           NaN
2023-01-04  1.885765      -1.203967           NaN
2023-01-05  1.433257       1.885765           NaN
2023-01-06  0.423468       1.433257           NaN
2023-01-07 -1.638003       0.423468      0.226034
2023-01-08  0.435742      -1.638003      0.139459
2023-01-09 -0.118356       0.435742      0.173987
2023-01-10  0.621007      -0.118356      0.434697