In [2]:
import pandas as pd
import numpy as np
from pathlib import Path
path_str = r"C:\Users\konta\Documents\DIV_Academy\Module2(From_29_nov)\data\world_population.csv"
csv_path = Path(path_str)
df = pd.read_csv(csv_path)
df

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [3]:
df2 = df.set_index('CCA3')
df2

,Rank,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
CCA3,,,,,,,,,,,,,,,,
AFG,36,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
ALB,138,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
DZA,34,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
ASM,213,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
AND,203,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WLF,226,Wallis and Futuna,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
ESH,172,Western Sahara,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
YEM,46,Yemen,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
ZMB,63,Zambia,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
ZWE,74,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [5]:
df2.head(3)

,Rank,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
CCA3,,,,,,,,,,,,,,,,
AFG,36,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
ALB,138,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
DZA,34,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56

In [11]:
df_pop = df2.loc['AFG': 'AZE', ['Country', '2022 Population']]
df_area = df2.iloc[10:20, [1, -4]]
df_area

         Country  Area (km²)
CCA3
ABW        Aruba       180.0
AUS    Australia   7692024.0
AUT      Austria     83871.0
AZE   Azerbaijan     86600.0
BHS      Bahamas     13943.0
BHR      Bahrain       765.0
BGD   Bangladesh    147570.0
BRB     Barbados       430.0
BLR      Belarus    207600.0
BEL      Belgium     30528.0

In [21]:
adamlar = ['shahriyar', 'nijat', 'murad', 'asgar', 'aynur']
yemekler = ['dolma', 'katlet', 'ash', 'lule', 'bughlama']
rengler = ['cyan', 'qara', 'yashil', 'sari', 'goy']

s_yemek = pd.Series(yemekler, index=adamlar, name='Food')
s_reng = pd.Series(rengler, index=adamlar, name='Color')

In [23]:
pd.concat([s_yemek, s_reng], ignore_index=False, axis=1)

               Food   Color
shahriyar     dolma    cyan
nijat        katlet    qara
murad           ash  yashil
asgar          lule    sari
aynur      bughlama     goy

In [26]:
pd.concat(
    [df_pop, df_area],
    axis=1
).head(3)

          Country  2022 Population Country  Area (km²)
CCA3
AFG   Afghanistan       41128771.0     NaN         NaN
ALB       Albania        2842321.0     NaN         NaN
DZA       Algeria       44903225.0     NaN         NaN

In [33]:
yemekler = ['dolma', 'katlet', 'ash', 'lule', 'xengel']
adamlar_y = ['shahriyar', 'nijat', 'murad', 'asgar', 'isa']

rengler = ['cyan', 'qara', 'yashil', 'sari']
adamlar_r = ['shahriyar', 'nijat', 'murad', 'aynur']

s_yemek = pd.Series(yemekler, index=adamlar_y, name='yemek')
s_reng = pd.Series(rengler, index=adamlar_r, name='reng')

In [35]:
pd.merge(left=s_yemek, right=s_reng, how='left', left_index=True, right_index=True)

            yemek    reng
shahriyar   dolma    cyan
nijat      katlet    qara
murad         ash  yashil
asgar        lule     NaN
isa        xengel     NaN

In [36]:
pd.merge(left=s_yemek, right=s_reng, how='outer', left_index=True, right_index=True)

            yemek    reng
asgar        lule     NaN
aynur         NaN    sari
isa        xengel     NaN
murad         ash  yashil
nijat      katlet    qara
shahriyar   dolma    cyan

In [37]:
pd.merge(left=s_yemek, right=s_reng, left_index=True, right_index=True)

            yemek    reng
shahriyar   dolma    cyan
nijat      katlet    qara
murad         ash  yashil

In [38]:
df_area.head(3)

        Country  Area (km²)
CCA3
ABW       Aruba       180.0
AUS   Australia   7692024.0
AUT     Austria     83871.0

In [39]:
df_pop.head(3)

          Country  2022 Population
CCA3
AFG   Afghanistan       41128771.0
ALB       Albania        2842321.0
DZA       Algeria       44903225.0

In [47]:
pd.merge(df_pop, df_area.drop('Country', axis=1), how='inner', left_index=True, right_index=True, suffixes=['_pop', '_area'])

         Country  2022 Population  Area (km²)
CCA3
ABW        Aruba         106445.0       180.0
AUS    Australia       26177413.0   7692024.0
AUT      Austria        8939617.0     83871.0
AZE   Azerbaijan       10358074.0     86600.0

In [ ]:
pd.merge(df_pop, df_area, how='inner', on='Country')

      Country  2022 Population  Area (km²)
0       Aruba         106445.0       180.0
1   Australia       26177413.0   7692024.0
2     Austria        8939617.0     83871.0
3  Azerbaijan       10358074.0     86600.0

In [55]:
rng = np.random.RandomState(0)  ### ring and seed inside of it 
df = pd.DataFrame({
    'key': ['A', 'B', 'C', 'A', 'B', 'C'],
    'data1': range(6),
    'data2': rng.randint(0, 10, 6)},
    columns = ['key', 'data1', 'data2'])
print(df)

  key  data1  data2
0   A      0      5
1   B      1      0
2   C      2      3
3   A      3      3
4   B      4      7
5   C      5      9

In [61]:
rng = np.random.RandomState(0)
data2 = rng.randint(0, 10, 6)
data1 = np.arange(6)

df = pd.DataFrame(
    {
        's': ['A', 'B', 'C'] * 2,
        'data1': data1,
        'data2': data2,
    }
)

In [ ]:
df.groupby(by='s')['data1']

In [67]:
df.groupby(by='s')['data1'].agg(['mean', 'sum', 'count'])

   mean  sum  count
s
A   1.5    3      2
B   2.5    5      2
C   3.5    7      2

In [69]:
df2.groupby('Continent')['2022 Population'].mean()

Continent
Africa           2.545588e+07
Asia             9.632739e+07
Europe           1.505537e+07
North America    1.500740e+07
Oceania          2.046386e+06
South America    3.120119e+07
Name: 2022 Population, dtype: float64

In [84]:
df2.groupby('Continent')['2022 Population'].agg(['mean', 'sum', 'count', 'min'])

                       mean           sum  count       min
Continent
Africa         2.545588e+07  1.425529e+09     56  107118.0
Asia           9.632739e+07  4.720042e+09     49  449002.0
Europe         1.505537e+07  7.377132e+08     49     510.0
North America  1.500740e+07  6.002961e+08     40    4390.0
Oceania        2.046386e+06  4.502050e+07     22    1871.0
South America  3.120119e+07  4.368166e+08     14    3780.0

In [80]:
df3 = df2.loc[:, 'Continent':]

<class 'pandas.core.frame.DataFrame'>
Index: 234 entries, AFG to ZWE
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Continent                    234 non-null    object
 1   2022 Population              230 non-null    float64
 2   2020 Population              233 non-null    float64
 3   2015 Population              230 non-null    float64
 4   2010 Population              227 non-null    float64
 5   2000 Population              227 non-null    float64
 6   1990 Population              229 non-null    float64
 7   1980 Population              229 non-null    float64
 8   1970 Population              230 non-null    float64
 9   Area (km²)                   232 non-null    float64
 10  Density (per km²)            230 non-null    float64
 11  Growth Rate                  232 non-null    float64
 12  World Population Percentage  234 non-null    float64
dtypes: float64(12), object(1)
memory usage: 33.7+ KB

In [ ]:
df3.describe()

,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
count,2.300000e+02,2.330000e+02,2.300000e+02,2.270000e+02,2.270000e+02,2.290000e+02,2.290000e+02,2.300000e+02,2.320000e+02,230.000000,232.000000,234.000000
mean,3.463225e+07,3.360071e+07,3.206600e+07,3.027016e+07,2.684050e+07,1.933046e+07,1.628288e+07,1.586650e+07,5.816637e+05,456.811652,1.009553,0.427051
std,1.378892e+08,1.358732e+08,1.315071e+08,1.260742e+08,1.133525e+08,8.130962e+07,6.934547e+07,6.835586e+07,1.769133e+06,2083.740364,0.013390,1.714977
min,5.100000e+02,5.200000e+02,5.640000e+02,5.960000e+02,6.510000e+02,7.000000e+02,7.330000e+02,7.520000e+02,1.000000e+00,0.026100,0.912000,0.000000
25%,4.197385e+05,4.064710e+05,3.942950e+05,3.827265e+05,3.294700e+05,2.619280e+05,2.237520e+05,1.458805e+05,2.567250e+03,36.598125,1.001925,0.010000
50%,5.762857e+06,5.456681e+06,5.244415e+06,4.889741e+06,4.491202e+06,3.785847e+06,3.135123e+06,2.511718e+06,7.714100e+04,95.346750,1.007900,0.070000
75%,2.265372e+07,2.152263e+07,1.973085e+07,1.682585e+07,1.562547e+07,1.188276e+07,9.817257e+06,8.817329e+06,4.146432e+05,236.884000,1.016650,0.280000
max,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,9.823725e+08,8.225344e+08,1.709824e+07,23172.266700,1.069100,17.880000

In [ ]:
df3.groupby('Continent')['2022 Population'].mean()

Continent
Africa           2.545588e+07
Asia             9.632739e+07
Europe           1.505537e+07
North America    1.500740e+07
Oceania          2.046386e+06
South America    3.120119e+07
Name: 2022 Population, dtype: float64

In [86]:
df3.groupby('Continent').mean()

,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Continent,,,,,,,,,,,,
Africa,2.545588e+07,2.387144e+07,2.141970e+07,1.889820e+07,1.459837e+07,1.137696e+07,8.586032e+06,6.567175e+06,5.378793e+05,126.406569,1.021180,0.313509
Asia,9.632739e+07,9.495513e+07,8.916500e+07,8.908777e+07,8.058084e+07,4.864000e+07,4.027833e+07,4.383988e+07,6.427628e+05,1025.024136,1.009384,1.183800
Europe,1.505537e+07,1.491584e+07,1.502745e+07,1.471228e+07,1.481769e+07,1.478520e+07,1.420000e+07,1.311848e+07,4.602082e+05,663.324742,1.002256,0.186600
North America,1.500740e+07,1.485591e+07,1.425960e+07,1.356802e+07,1.215174e+07,1.053166e+07,9.207334e+06,7.885865e+06,6.061044e+05,272.494118,1.004285,0.187750
Oceania,2.046386e+06,1.910149e+06,1.756664e+06,1.613164e+06,1.357512e+06,1.162775e+06,9.965322e+05,8.469683e+05,3.702209e+05,132.543065,1.007383,0.023913
South America,3.120119e+07,3.082357e+07,2.950960e+07,2.678940e+07,2.501589e+07,2.122474e+07,1.727064e+07,1.378194e+07,1.301303e+06,20.971979,1.007957,0.391429

In [87]:
df3.groupby('Continent').agg({
   '2022 Population':'mean'
})

               2022 Population
Continent
Africa            2.545588e+07
Asia              9.632739e+07
Europe            1.505537e+07
North America     1.500740e+07
Oceania           2.046386e+06
South America     3.120119e+07

In [ ]:
df3.groupby('Continent').agg(
    pop_2022 = {'2022 Population':'mean'}
)

TypeError: Must provide 'func' or tuples of '(column, aggfunc).

In [ ]:
### 18 december

df1 = pd.DataFrame({
    'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
    'group': ['Accounting', 'Engineering','Engineering', 'HR']})
df2 = pd.DataFrame({
    'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
    'hire_date': [2004, 2008, 2012, 2014]})

df1

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

In [8]:
df2

  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

In [7]:
df3 = pd.merge(df1, df2, on='employee')
df3

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [23]:
from pathlib import Path

car_path = Path(r"C:\Users\konta\Documents\DIV_Academy\Module2(From_29_nov)\data\car-sales-extended.csv")
births_path = Path(r"C:\Users\konta\Documents\DIV_Academy\Module2(From_29_nov)\data\births.csv")


birth = pd.read_csv(births_path)
cars = pd.read_csv(car_path)
birth

       year  month  day gender  births
0      1969      1  1.0      F    4046
1      1969      1  1.0      M    4440
2      1969      1  2.0      F    4454
3      1969      1  2.0      M    4548
4      1969      1  3.0      F    4548
...     ...    ...  ...    ...     ...
15542  2008     10  NaN      M  183219
15543  2008     11  NaN      F  158939
15544  2008     11  NaN      M  165468
15545  2008     12  NaN      F  173215
15546  2008     12  NaN      M  181235

[15547 rows x 5 columns]

In [17]:
cars

       Make Colour  Odometer (KM)  Doors  Price
0     Honda  White          35431      4  15323
1       BMW   Blue         192714      5  19943
2     Honda  White          84714      4  28343
3    Toyota  White         154365      4  13434
4    Nissan   Blue         181577      3  14043
..      ...    ...            ...    ...    ...
995  Toyota  Black          35820      4  32042
996  Nissan  White         155144      3   5716
997  Nissan   Blue          66604      4  31570
998   Honda  White         215883      4   4001
999  Toyota   Blue         248360      4  12732

[1000 rows x 5 columns]

In [ ]:
df = pd.DataFrame({
    'key': ['A', 'B', 'C', 'A', 'B', 'C'],
    'data': range(6)
    })

df.groupby('key').agg({
    'data': 'mean'
})

     data
key
A     1.5
B     2.5
C     3.5

In [22]:
birth.groupby('year')['births'].mean()

year
1969      4687.768229
1970      4866.927083
1971      4664.329843
1972      4269.588235
1973      4128.772966
1974      4139.204961
1975      4133.100917
1976      4174.081472
1977      4378.658344
1978      4386.727989
1979      4685.133869
1980      4843.348059
1981      4879.885906
1982      4927.081551
1983      4863.579439
1984      4917.761714
1985      5108.635007
1986      5109.639946
1987      5202.204638
1988      5296.066306
1989    168570.541667
1990    173454.875000
1991    171472.583333
1992    169559.500000
1993    166855.125000
1994    164871.875000
1995    162625.500000
1996    162286.416667
1997    161847.041667
1998    164383.000000
1999    165144.375000
2000    169325.958333
2001    167980.458333
2002    167807.333333
2003    170670.500000
2004    171621.125000
2005    172734.125000
2006    178051.041667
2007    180167.000000
2008    177298.166667
Name: births, dtype: float64

In [25]:
birth.groupby(['year', 'month', 'day'])['births'].sum()

year  month  day
1969  1      1.0      8486
             2.0      9002
             3.0      9542
             4.0      8960
             5.0      8390
                     ...
1988  12     27.0    11528
             28.0    11847
             29.0    11704
             30.0    11837
             31.0     9133
Name: births, Length: 7567, dtype: int64

In [30]:
birth.groupby(['year', 'month'])['births'].sum().mean()

np.float64(316196.62083333335)

In [31]:
birth.groupby('year').agg({'births':'sum'})

       births
year
1969  3600206
1970  3737800
1971  3563548
1972  3266235
1973  3146125
1974  3170631
1975  3153556
1976  3176476
1977  3332159
1978  3338300
1979  3499795
1980  3617981
1981  3635515
1982  3685457
1983  3642821
1984  3673568
1985  3765064
1986  3760695
1987  3813216
1988  3913793
1989  4045693
1990  4162917
1991  4115342
1992  4069428
1993  4004523
1994  3956925
1995  3903012
1996  3894874
1997  3884329
1998  3945192
1999  3963465
2000  4063823
2001  4031531
2002  4027376
2003  4096092
2004  4118907
2005  4145619
2006  4273225
2007  4324008
2008  4255156

In [33]:
birth.groupby(['year', 'month']).agg(
    {
        'births': 'sum'
    }
).mean()

births    316196.620833
dtype: float64

In [35]:
birth.groupby('gender')['births'].sum()

gender
F    74035823
M    77738555
Name: births, dtype: int64

In [36]:
birth.groupby('gender')['births'].mean()

gender
F     9521.067773
M    10003.674559
Name: births, dtype: float64

In [38]:
rng = np.random.RandomState(0)
df = pd.DataFrame({
    'key': ['A', 'B', 'C', 'A', 'B', 'C'],
    'data1': range(6),
    'data2': rng.randint(0, 10, 6)
    })
df

  key  data1  data2
0   A      0      5
1   B      1      0
2   C      2      3
3   A      3      3
4   B      4      7
5   C      5      9

In [40]:
# df.groupby('key')['data1'].sum()

df.groupby('key').agg(
    {
        'data1': 'sum'
    }
)

     data1
key
A        3
B        5
C        7

In [ ]:
# df.groupby('key')[['data1', 'data2']].sum()


df.groupby('key').agg(
    {
        'data1': ['sum', 'mean'], 'data2':'mean'  #multiindex
    }
)

    data1      data2
      sum mean  mean
key
A       3  1.5   4.0
B       5  2.5   3.5
C       7  3.5   6.0

In [49]:
cars.groupby('Make').agg({
    'Price': ['sum', 'min', 'mean']
})

          Price
            sum   min          mean
Make
BMW     2708983  9362  27089.830000
Honda   4412317  3509  14514.200658
Nissan  2704357  2796  13658.368687
Toyota  6220008  3125  15628.160804

In [52]:
cars.groupby(['Make', 'Colour']).agg(
    {
        'Price': 'mean'
    }
)

                      Price
Make   Colour
BMW    Black   24706.000000
       Blue    28845.058824
       Green   19438.750000
       Red     22510.230769
       White   29255.675676
Honda  Black   13926.031250
       Blue    14107.019231
       Green   17320.444444
       Red     15180.615385
       White   14460.403226
Nissan Black   13601.000000
       Blue    14078.483333
       Green   12509.562500
       Red     13069.166667
       White   13710.505618
Toyota Black   16680.750000
       Blue    16069.764228
       Green   13585.783784
       Red     13848.756757
       White   15887.872611

In [54]:
birth.groupby('gender')['births'].mean()

gender
F     9521.067773
M    10003.674559
Name: births, dtype: float64

In [57]:
gender_avg = birth.groupby('gender')['births'].transform('mean')
birth['gender_avg'] = gender_avg

birth

       year  month  day gender  births    gender_avg
0      1969      1  1.0      F    4046   9521.067773
1      1969      1  1.0      M    4440  10003.674559
2      1969      1  2.0      F    4454   9521.067773
3      1969      1  2.0      M    4548  10003.674559
4      1969      1  3.0      F    4548   9521.067773
...     ...    ...  ...    ...     ...           ...
15542  2008     10  NaN      M  183219  10003.674559
15543  2008     11  NaN      F  158939   9521.067773
15544  2008     11  NaN      M  165468  10003.674559
15545  2008     12  NaN      F  173215   9521.067773
15546  2008     12  NaN      M  181235  10003.674559

[15547 rows x 6 columns]

In [59]:
cars.groupby('Make')['Price'].mean().to_frame()

               Price
Make
BMW     27089.830000
Honda   14514.200658
Nissan  13658.368687
Toyota  15628.160804

In [61]:
cars_make_mean = cars.groupby('Make')['Price'].transform('mean')

cars['make_mean'] = cars_make_mean

In [62]:
cars

       Make Colour  Odometer (KM)  Doors  Price     make_mean
0     Honda  White          35431      4  15323  14514.200658
1       BMW   Blue         192714      5  19943  27089.830000
2     Honda  White          84714      4  28343  14514.200658
3    Toyota  White         154365      4  13434  15628.160804
4    Nissan   Blue         181577      3  14043  13658.368687
..      ...    ...            ...    ...    ...           ...
995  Toyota  Black          35820      4  32042  15628.160804
996  Nissan  White         155144      3   5716  13658.368687
997  Nissan   Blue          66604      4  31570  13658.368687
998   Honda  White         215883      4   4001  14514.200658
999  Toyota   Blue         248360      4  12732  15628.160804

[1000 rows x 6 columns]

In [65]:
m = cars['make_mean'] > cars['Price']

In [66]:
cars[m]

       Make Colour  Odometer (KM)  Doors  Price     make_mean
1       BMW   Blue         192714      5  19943  27089.830000
3    Toyota  White         154365      4  13434  15628.160804
6    Toyota   Blue         163453      4   8473  15628.160804
8    Nissan  White         130538      4   9374  13658.368687
11   Nissan  Green          17119      4   6160  13658.368687
..      ...    ...            ...    ...    ...           ...
991   Honda   Blue         235985      4   9184  14514.200658
993  Nissan  Black         162523      4   4696  13658.368687
996  Nissan  White         155144      3   5716  13658.368687
998   Honda  White         215883      4   4001  14514.200658
999  Toyota   Blue         248360      4  12732  15628.160804

[567 rows x 6 columns]

In [67]:
mask = cars['Price'] - cars['make_mean'] < 0

cars[mask]

       Make Colour  Odometer (KM)  Doors  Price     make_mean
1       BMW   Blue         192714      5  19943  27089.830000
3    Toyota  White         154365      4  13434  15628.160804
6    Toyota   Blue         163453      4   8473  15628.160804
8    Nissan  White         130538      4   9374  13658.368687
11   Nissan  Green          17119      4   6160  13658.368687
..      ...    ...            ...    ...    ...           ...
991   Honda   Blue         235985      4   9184  14514.200658
993  Nissan  Black         162523      4   4696  13658.368687
996  Nissan  White         155144      3   5716  13658.368687
998   Honda  White         215883      4   4001  14514.200658
999  Toyota   Blue         248360      4  12732  15628.160804

[567 rows x 6 columns]

In [ ]:
# cars.groupby('Make')['Price'].mean()
def less_than_avg(small_df):
    return small_df['Price'].std() < small_df['Price'].mean()

cars.groupby('Make').filter(less_than_avg)

8630.79421870436

### 20 december_continue

In [2]:
import pathlib
import pandas as pd

csv_path = pathlib.Path(r"C:\Users\konta\Documents\DIV_Academy\Module2(From_29_nov)\data\1.04. Real-life example.csv")
df = pd.read_csv(csv_path)
df

,Brand,Price,Body,Mileage,EngineV,Engine Type,Registration,Year,Model
0,BMW,4200.0,sedan,277,2.0,Petrol,yes,1991,320
1,Mercedes-Benz,7900.0,van,427,2.9,Diesel,yes,1999,Sprinter 212
2,Mercedes-Benz,13300.0,sedan,358,5.0,Gas,yes,2003,S 500
3,Audi,23000.0,crossover,240,4.2,Petrol,yes,2007,Q7
4,Toyota,18300.0,crossover,120,2.0,Petrol,yes,2011,Rav 4
...,...,...,...,...,...,...,...,...,...
4340,Mercedes-Benz,125000.0,sedan,9,3.0,Diesel,yes,2014,S 350
4341,BMW,6500.0,sedan,1,3.5,Petrol,yes,1999,535
4342,BMW,8000.0,sedan,194,2.0,Petrol,yes,1985,520
4343,Toyota,14200.0,sedan,31,NaN,Petrol,yes,2014,Corolla
4344,Volkswagen,13500.0,van,124,2.0,Diesel,yes,2013,T5 (Transporter)

In [3]:
df_yeni = df.copy()
df_yeni.set_index('Brand', inplace=True)

yeni_cols = [
['General', 'General', 'General', 'General', 'Main', 'Main', 'Main', 'Main'],
['Price', 'Body', 'Mileage', 'EngineV', 'Engine Type', 'Registration', 'Year', 'Model']
]

df_yeni.columns = yeni_cols
df_yeni.head(3)

               General                               Main                     \
                 Price   Body Mileage EngineV Engine Type Registration  Year
Brand
BMW             4200.0  sedan     277     2.0      Petrol          yes  1991
Mercedes-Benz   7900.0    van     427     2.9      Diesel          yes  1999
Mercedes-Benz  13300.0  sedan     358     5.0         Gas          yes  2003


                      Model
Brand
BMW                     320
Mercedes-Benz  Sprinter 212
Mercedes-Benz         S 500

In [4]:
mask = df_yeni.loc[:, ('General', 'Body')] != 'sedan'
df_yeni.loc[mask]

                General                                   Main               \
                  Price       Body Mileage EngineV Engine Type Registration
Brand
Mercedes-Benz    7900.0        van     427     2.9      Diesel          yes
Audi            23000.0  crossover     240     4.2      Petrol          yes
Toyota          18300.0  crossover     120     2.0      Petrol          yes
Mercedes-Benz  199999.0  crossover       0     5.5      Petrol          yes
Audi            14200.0      vagon     200     2.7      Diesel          yes
...                 ...        ...     ...     ...         ...          ...
Renault          7000.0        van     210     1.5      Diesel          yes
BMW             12090.0      hatch     145     1.6      Petrol          yes
Renault          2100.0      vagon     237     1.9      Diesel           no
Volkswagen      11500.0        van     163     2.5      Diesel          yes
Volkswagen      13500.0        van     124     2.0      Diesel          yes


               Year              Model
Brand
Mercedes-Benz  1999       Sprinter 212
Audi           2007                 Q7
Toyota         2011              Rav 4
Mercedes-Benz  2016             GLS 63
Audi           2006                 A6
...             ...                ...
Renault        2005             Kangoo
BMW            2010                116
Renault        2001             Laguna
Volkswagen     2008   T5 (Transporter)
Volkswagen     2013  T5 (Transporter)

[2696 rows x 8 columns]

In [9]:
mask = (df['Body'] == 'crossover') | (df['Body'] == 'hatch')

df[mask].groupby(['Brand', 'Body']).agg({
    'Price': 'sum',
    'Mileage': 'mean',
    'Model': 'nunique'
})

                              Price     Mileage  Model
Brand         Body
Audi          crossover  2856303.25   98.753247      5
              hatch       367214.00  123.157895      6
BMW           crossover  7342248.00  103.125654      7
              hatch       226112.00  109.750000      7
Mercedes-Benz crossover  9490101.00   90.148810     31
              hatch       336956.00  126.391304     11
Mitsubishi    crossover  2165697.85  121.875912      7
              hatch        90435.25  204.473684      5
Renault       crossover   263093.41   72.263158      6
              hatch       302317.15  124.658537     10
Toyota        crossover  7202984.94  114.273543     17
              hatch       586874.39   96.101695      7
Volkswagen    crossover  2514893.55  109.779070      6
              hatch       904019.78  153.723214     16

In [11]:
df.groupby('Brand')['Price'].mean()
df2 = df.groupby('Brand', as_index=False).agg({
    'Price' : 'mean'
})
df3 = df.drop('brand_avg', axis='columns')
pd.merge(df3, df2, how='left', on='Brand')

NameError: name 'df3' is not defined

In [ ]:
# df.loc[:, 'EngineV'].unique().sort()
# df

,Brand,Price,Body,Mileage,EngineV,Engine Type,Registration,Year,Model
0,BMW,4200.0,sedan,277,2.0,Petrol,yes,1991,320
1,Mercedes-Benz,7900.0,van,427,2.9,Diesel,yes,1999,Sprinter 212
2,Mercedes-Benz,13300.0,sedan,358,5.0,Gas,yes,2003,S 500
3,Audi,23000.0,crossover,240,4.2,Petrol,yes,2007,Q7
4,Toyota,18300.0,crossover,120,2.0,Petrol,yes,2011,Rav 4
...,...,...,...,...,...,...,...,...,...
4340,Mercedes-Benz,125000.0,sedan,9,3.0,Diesel,yes,2014,S 350
4341,BMW,6500.0,sedan,1,3.5,Petrol,yes,1999,535
4342,BMW,8000.0,sedan,194,2.0,Petrol,yes,1985,520
4343,Toyota,14200.0,sedan,31,NaN,Petrol,yes,2014,Corolla
4344,Volkswagen,13500.0,van,124,2.0,Diesel,yes,2013,T5 (Transporter)

In [15]:
df.groupby('Model')['EngineV'].min().head(3)

Model
1 Series    1.6
100         2.0
11          1.4
Name: EngineV, dtype: float64

In [19]:
df.groupby('Model').filter(lambda small_df:small_df['EngineV'].min() > 2)

,Brand,Price,Body,Mileage,EngineV,Engine Type,Registration,Year,Model
1,Mercedes-Benz,7900.0,van,427,2.9,Diesel,yes,1999,Sprinter 212
2,Mercedes-Benz,13300.0,sedan,358,5.0,Gas,yes,2003,S 500
3,Audi,23000.0,crossover,240,4.2,Petrol,yes,2007,Q7
5,Mercedes-Benz,199999.0,crossover,0,5.5,Petrol,yes,2016,GLS 63
12,Audi,9500.0,vagon,165,2.7,Gas,yes,2003,A6 Allroad
...,...,...,...,...,...,...,...,...,...
4327,Audi,80999.0,crossover,0,3.0,Diesel,yes,2016,Q7
4330,BMW,21335.0,other,105,3.0,Petrol,yes,2008,335
4331,BMW,45000.0,crossover,80,3.0,Petrol,yes,2011,X6
4340,Mercedes-Benz,125000.0,sedan,9,3.0,Diesel,yes,2014,S 350
4341,BMW,6500.0,sedan,1,3.5,Petrol,yes,1999,535

In [24]:
df_excel = df.groupby(['Brand', 'Body']).agg({
    'Price':'mean'
})

In [22]:
df.groupby(['Brand', 'Body']).agg({
    'Price':'mean'
}).unstack()

                      Price                                            \
Body              crossover         hatch         other         sedan
Brand
Audi           39127.441781  20400.777778  28293.285714  14171.281100
BMW            41955.702857  20555.636364  23736.474576  16129.906414
Mercedes-Benz  66831.697183  14650.260870  33092.544776  23080.077135
Mitsubishi     16042.206296   4759.750000  11783.507692   7659.484375
Renault        13847.021579   7373.589024   8645.147059   7156.349655
Toyota         34137.369384  10296.041930  23919.135135  14078.361768
Volkswagen     29586.982941   8218.361636  11640.494624  12413.651241


Body                  vagon           van
Brand
Audi            9375.830189   3000.000000
BMW            14477.023810           NaN
Mercedes-Benz  11924.500000  18823.770588
Mitsubishi      7700.000000   6285.285714
Renault         8381.641481   7573.402041
Toyota         15147.937500  21381.250000
Volkswagen      9583.586596  12359.136846

In [23]:
df.pivot_table(
    values='Price',
    index='Brand',
    columns='Body',
    aggfunc='mean'
)

Body,crossover,hatch,other,sedan,vagon,van
Brand,,,,,,
Audi,39127.441781,20400.777778,28293.285714,14171.281100,9375.830189,3000.000000
BMW,41955.702857,20555.636364,23736.474576,16129.906414,14477.023810,NaN
Mercedes-Benz,66831.697183,14650.260870,33092.544776,23080.077135,11924.500000,18823.770588
Mitsubishi,16042.206296,4759.750000,11783.507692,7659.484375,7700.000000,6285.285714
Renault,13847.021579,7373.589024,8645.147059,7156.349655,8381.641481,7573.402041
Toyota,34137.369384,10296.041930,23919.135135,14078.361768,15147.937500,21381.250000
Volkswagen,29586.982941,8218.361636,11640.494624,12413.651241,9583.586596,12359.136846

In [28]:
df_excel.reset_index().to_excel('Excel_Pivot1.xlsx')

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4345 entries, 0 to 4344
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Brand         4345 non-null   object
 1   Price         4173 non-null   float64
 2   Body          4345 non-null   object
 3   Mileage       4345 non-null   int64
 4   EngineV       4195 non-null   float64
 5   Engine Type   4345 non-null   object
 6   Registration  4345 non-null   object
 7   Year          4345 non-null   int64
 8   Model         4345 non-null   object
dtypes: float64(2), int64(2), object(5)
memory usage: 305.6+ KB

In [34]:
df['Brand'].str.replace('Toy', 'TOY', regex=False)

0                 BMW
1       Mercedes-Benz
2       Mercedes-Benz
3                Audi
4              TOYota
            ...
4340    Mercedes-Benz
4341              BMW
4342              BMW
4343           TOYota
4344       Volkswagen
Name: Brand, Length: 4345, dtype: object

In [36]:
from datetime import datetime, timedelta

In [41]:
BD = datetime(year=1887, month=10, day=2)
today = datetime.today()
today

datetime.datetime(2025, 12, 20, 20, 46, 49, 969059)

In [ ]:
td = (today - BD)

50483

In [52]:
tdi = pd.Timestamp(today) - pd.Timestamp(BD)

In [54]:
tdi / 30 / 12

Timedelta('140 days 05:35:27.805469')

In [56]:
pd.timedelta_range(start='1 day', periods=2, freq='d')

TimedeltaIndex(['1 days', '2 days'], dtype='timedelta64[ns]', freq='D')

In [57]:
%pip install yFinance

Collecting yFinance
  Downloading yfinance-0.2.66-py2.py3-none-any.whl.metadata (6.0 kB)
Requirement already satisfied: pandas>=1.3.0 in c:\users\konta\anaconda3\envs\ds\lib\site-packages (from yFinance) (2.3.3)
Requirement already satisfied: numpy>=1.16.5 in c:\users\konta\anaconda3\envs\ds\lib\site-packages (from yFinance) (2.3.4)
Collecting requests>=2.31 (from yFinance)
  Downloading requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
Collecting multitasking>=0.0.7 (from yFinance)
  Downloading multitasking-0.0.12.tar.gz (19 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: platformdirs>=2.0.0 in c:\users\konta\anaconda3\envs\ds\lib\site-packages (from yFinance) (4.5.0)
Requirement already satisfied: pytz>=2022.5 in c:\users\konta\anaconda3\envs\ds\lib\site-packages (from yFinance) (2025.2)
Collecting frozendict>=2.3.4 (from yFinance)
  Downloading frozendict-2.4.7-py3-none-any.whl.metadata (23 kB)
Collecting peewee>=3.16.2 (from yFinance)
  Downloading peewee-3.18.3.tar.gz (3.0 MB)
     ---------------------------------------- 0.0/3.0 MB ? eta -:--:--
     --- ------------------------------------ 0.3/3.0 MB ? eta -:--:--
     -------------------- ------------------- 1.6/3.0 MB 5.6 MB/s eta 0:00:01
     ---------------------------------------- 3.0/3.0 MB 7.7 MB/s  0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting beautifulsoup4>=4.11.1 (from yFinance)
  Downloading beautifulsoup4-4.14.3-py3-none-any.whl.metadata (3.8 kB)
Collecting curl_cffi>=0.7 (from yFinance)
  Downloading curl_cffi-0.14.0-cp39-abi3-win_amd64.whl.metadata (15 kB)
Collecting protobuf>=3.19.0 (from yFinance)
  Downloading protobuf-6.33.2-cp310-abi3-win_amd64.whl.metadata (593 bytes)
Collecting websockets>=13.0 (from yFinance)
  Downloading websockets-15.0.1-cp311-cp311-win_amd64.whl.metadata (7.0 kB)
Collecting soupsieve>=1.6.1 (from beautifulsoup4>=4.11.1->yFinance)
  Downloading soupsieve-2.8.1-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\konta\anaconda3\envs\ds\lib\site-packages (from beautifulsoup4>=4.11.1->yFinance) (4.15.0)
Collecting cffi>=1.12.0 (from curl_cffi>=0.7->yFinance)
  Downloading cffi-2.0.0-cp311-cp311-win_amd64.whl.metadata (2.6 kB)
Collecting certifi>=2024.2.2 (from curl_cffi>=0.7->yFinance)
  Using cached certifi-2025.11.12-py3-none-any.whl.metadata (2.5 kB)
Collecting pycparser (from cffi>=1.12.0->curl_cffi>=0.7->yFinance)
  Downloading pycparser-2.23-py3-none-any.whl.metadata (993 bytes)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\konta\anaconda3\envs\ds\lib\site-packages (from pandas>=1.3.0->yFinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\konta\anaconda3\envs\ds\lib\site-packages (from pandas>=1.3.0->yFinance) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\konta\anaconda3\envs\ds\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yFinance) (1.17.0)
Collecting charset_normalizer<4,>=2 (from requests>=2.31->yFinance)
  Downloading charset_normalizer-3.4.4-cp311-cp311-win_amd64.whl.metadata (38 kB)
Collecting idna<4,>=2.5 (from requests>=2.31->yFinance)
  Using cached idna-3.11-py3-none-any.whl.metadata (8.4 kB)
Collecting urllib3<3,>=1.21.1 (from requests>=2.31->yFinance)
  Downloading urllib3-2.6.2-py3-none-any.whl.metadata (6.6 kB)
Downloading yfinance-0.2.66-py2.py3-none-any.whl (123 kB)
Downloading beautifulsoup4-4.14.3-py3-none-any.whl (107 kB)
Downloading curl_cffi-0.14.0-cp39-abi3-win_amd64.whl (1.7 MB)
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ------------------------------------- -- 1.6/1.7 MB 8.4 MB/s eta 0:00:01
   ---------------------------------------- 1.7/1.7 MB 6.5 MB/s  0:00:00
Using cached certifi-2025.11.12-py3-none-any.whl (159 kB)
Downloading cffi-2.0.0-cp311-cp311-win_amd64.whl (182 kB)
Downloading frozendict-2.4.7-py3-none-any.whl (16 kB)
Downloading protobuf-6.33.2-cp310-abi3-win_amd64.whl (436 kB)
Downloading requests-2.32.5-py3-none-any.whl (64 kB)
Downloading charset_normalizer-3.4.4-cp311-cp311-win_amd64.whl (106 kB)
Using cached idna-3.11-py3-none-any.whl (71 kB)
Downloading urllib3-2.6.2-py3-none-any.whl (131 kB)
Downloading soupsieve-2.8.1-py3-none-any.whl (36 kB)
Downloading websockets-15.0.1-cp311-cp311-win_amd64.whl (176 kB)
Downloading pycparser-2.23-py3-none-any.whl (118 kB)
Building wheels for collected packages: multitasking, peewee
  Building wheel for multitasking (setup.py): started
  Building wheel for multitasking (setup.py): finished with status 'done'
  Created wheel for multitasking: filename=multitasking-0.0.12-py3-none-any.whl size=15703 sha256=69735830d9ce9664efcccfd6997cc6cbd22c1e0754ccb31a3698478493c59268
  Stored in directory: c:\users\konta\appdata\local\pip\cache\wheels\42\d6\84\bf57a755f4569494cd00de4bb46ef064874823f4d19c82e960
  Building wheel for peewee (pyproject.toml): started
  Building wheel for peewee (pyproject.toml): finished with status 'done'
  Created wheel for peewee: filename=peewee-3.18.3-py3-none-any.whl size=139181 sha256=779e73c40333b15baf61ba5994a6ad589a62cecc9643001e28355c7f9c2786a1
  Stored in directory: c:\users\konta\appdata\local\pip\cache\wheels\05\dc\94\4ba26d23cac9aee7481d3dfcc7e99ce2cc5731230ec10f7ec1
Successfully built multitasking peewee
Installing collected packages: peewee, multitasking, websockets, urllib3, soupsieve, pycparser, protobuf, idna, frozendict, charset_normalizer, certifi, requests, cffi, beautifulsoup4, curl_cffi, yFinance

   ----------------------------------------  0/16 [peewee]
   ----------------------------------------  0/16 [peewee]
   ----------------------------------------  0/16 [peewee]
   ----- ----------------------------------  2/16 [websockets]
   ----- ----------------------------------  2/16 [websockets]
   ------- --------------------------------  3/16 [urllib3]
   ---------- -----------------------------  4/16 [soupsieve]
   ------------ ---------------------------  5/16 [pycparser]
   --------------- ------------------------  6/16 [protobuf]
   --------------- ------------------------  6/16 [protobuf]
   --------------- ------------------------  6/16 [protobuf]
   ----------------- ----------------------  7/16 [idna]
   ---------------------- -----------------  9/16 [charset_normalizer]
   --------------------------- ------------ 11/16 [requests]
   ------------------------------ --------- 12/16 [cffi]
   ----------------------------------- ---- 14/16 [curl_cffi]
   ----------------------------------- ---- 14/16 [curl_cffi]
   ------------------------------------- -- 15/16 [yFinance]
   ---------------------------------------- 16/16 [yFinance]

Successfully installed beautifulsoup4-4.14.3 certifi-2025.11.12 cffi-2.0.0 charset_normalizer-3.4.4 curl_cffi-0.14.0 frozendict-2.4.7 idna-3.11 multitasking-0.0.12 peewee-3.18.3 protobuf-6.33.2 pycparser-2.23 requests-2.32.5 soupsieve-2.8.1 urllib3-2.6.2 websockets-15.0.1 yFinance-0.2.66
Note: you may need to restart the kernel to use updated packages.

  DEPRECATION: Building 'multitasking' using the legacy setup.py bdist_wheel mechanism, which will be removed in a future version. pip 25.3 will enforce this behaviour change. A possible replacement is to use the standardized build interface by setting the `--use-pep517` option, (possibly combined with `--no-build-isolation`), or adding a `pyproject.toml` file to the source tree of 'multitasking'. Discussion can be found at https://github.com/pypa/pip/issues/6334

In [3]:
import yfinance as yf
import datetime

tickers = ['NVDA']

start_date = datetime.datetime(2023, 1, 1)
end_date = datetime.datetime.now()
data = yf.download(tickers, start=start_date, end=end_date)
data = data.droplevel(axis=1, level=1)
data

C:\Users\konta\AppData\Local\Temp\ipykernel_9580\2727356413.py:8: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(tickers, start=start_date, end=end_date)
[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open     Volume
Date
2023-01-03   14.300684   14.981004   14.081903   14.836148  401277000
2023-01-04   14.734250   14.838146   14.226759   14.552433  431324000
2023-01-05   14.250735   14.549436   14.133852   14.476509  389168000
2023-01-06   14.844140   14.994989   14.019965   14.459525  405044000
2023-01-09   15.612371   16.039943   15.125858   15.268716  504231000
...                ...         ...         ...         ...        ...
2025-12-19  180.990005  181.449997  176.339996  176.669998  324925900
2025-12-22  183.690002  184.160004  182.350006  183.919998  129064400
2025-12-23  189.210007  189.330002  182.899994  182.970001  174873600
2025-12-24  188.610001  188.910004  186.589996  187.940002   65528500
2025-12-26  190.880005  192.289993  189.610001  189.960007   77987104

[749 rows x 5 columns]

In [4]:
data = data['Close']
data

data.groupby?

Signature:
data.groupby(
    by=None,
    axis: 'Axis' = 0,
    level: 'IndexLabel | None' = None,
    as_index: 'bool' = True,
    sort: 'bool' = True,
    group_keys: 'bool' = True,
    observed: 'bool | lib.NoDefault' = <no_default>,
    dropna: 'bool' = True,
) -> 'SeriesGroupBy'
Docstring:
Group Series using a mapper or by a Series of columns.

A groupby operation involves some combination of splitting the
object, applying a function, and combining the results. This can be
used to group large amounts of data and compute operations on these
groups.

Parameters
----------
by : mapping, function, label, pd.Grouper or list of such
    Used to determine the groups for the groupby.
    If ``by`` is a function, it's called on each value of the object's
    index. If a dict or Series is passed, the Series or dict VALUES
    will be used to determine the groups (the Series' values are first
    aligned; see ``.align()`` method). If a list or ndarray of length
    equal to the selected axis is passed (see the `groupby user guide
    <https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html#splitting-an-object-into-groups>`_),
    the values are used as-is to determine the groups. A label or list
    of labels may be passed to group by the columns in ``self``.
    Notice that a tuple is interpreted as a (single) key.
axis : {0 or 'index', 1 or 'columns'}, default 0
    Split along rows (0) or columns (1). For `Series` this parameter
    is unused and defaults to 0.

    .. deprecated:: 2.1.0

        Will be removed and behave like axis=0 in a future version.
        For ``axis=1``, do ``frame.T.groupby(...)`` instead.

level : int, level name, or sequence of such, default None
    If the axis is a MultiIndex (hierarchical), group by a particular
    level or levels. Do not specify both ``by`` and ``level``.
as_index : bool, default True
    Return object with group labels as the
    index. Only relevant for DataFrame input. as_index=False is
    effectively "SQL-style" grouped output. This argument has no effect
    on filtrations (see the `filtrations in the user guide
    <https://pandas.pydata.org/docs/dev/user_guide/groupby.html#filtration>`_),
    such as ``head()``, ``tail()``, ``nth()`` and in transformations
    (see the `transformations in the user guide
    <https://pandas.pydata.org/docs/dev/user_guide/groupby.html#transformation>`_).
sort : bool, default True
    Sort group keys. Get better performance by turning this off.
    Note this does not influence the order of observations within each
    group. Groupby preserves the order of rows within each group. If False,
    the groups will appear in the same order as they did in the original DataFrame.
    This argument has no effect on filtrations (see the `filtrations in the user guide
    <https://pandas.pydata.org/docs/dev/user_guide/groupby.html#filtration>`_),
    such as ``head()``, ``tail()``, ``nth()`` and in transformations
    (see the `transformations in the user guide
    <https://pandas.pydata.org/docs/dev/user_guide/groupby.html#transformation>`_).

    .. versionchanged:: 2.0.0

        Specifying ``sort=False`` with an ordered categorical grouper will no
        longer sort the values.

group_keys : bool, default True
    When calling apply and the ``by`` argument produces a like-indexed
    (i.e. :ref:`a transform <groupby.transform>`) result, add group keys to
    index to identify pieces. By default group keys are not included
    when the result's index (and column) labels match the inputs, and
    are included otherwise.

    .. versionchanged:: 1.5.0

       Warns that ``group_keys`` will no longer be ignored when the
       result from ``apply`` is a like-indexed Series or DataFrame.
       Specify ``group_keys`` explicitly to include the group keys or
       not.

    .. versionchanged:: 2.0.0

       ``group_keys`` now defaults to ``True``.

observed : bool, default False
    This only applies if any of the groupers are Categoricals.
    If True: only show observed values for categorical groupers.
    If False: show all values for categorical groupers.

    .. deprecated:: 2.1.0

        The default value will change to True in a future version of pandas.

dropna : bool, default True
    If True, and if group keys contain NA values, NA values together
    with row/column will be dropped.
    If False, NA values will also be treated as the key in groups.

Returns
-------
pandas.api.typing.SeriesGroupBy
    Returns a groupby object that contains information about the groups.

See Also
--------
resample : Convenience method for frequency conversion and resampling
    of time series.

Notes
-----
See the `user guide
<https://pandas.pydata.org/pandas-docs/stable/groupby.html>`__ for more
detailed usage and examples, including splitting an object into groups,
iterating through groups, selecting a group, aggregation, and more.

Examples
--------
>>> ser = pd.Series([390., 350., 30., 20.],
...                 index=['Falcon', 'Falcon', 'Parrot', 'Parrot'],
...                 name="Max Speed")
>>> ser
Falcon    390.0
Falcon    350.0
Parrot     30.0
Parrot     20.0
Name: Max Speed, dtype: float64
>>> ser.groupby(["a", "b", "a", "b"]).mean()
a    210.0
b    185.0
Name: Max Speed, dtype: float64
>>> ser.groupby(level=0).mean()
Falcon    370.0
Parrot     25.0
Name: Max Speed, dtype: float64
>>> ser.groupby(ser > 100).mean()
Max Speed
False     25.0
True     370.0
Name: Max Speed, dtype: float64

**Grouping by Indexes**

We can groupby different levels of a hierarchical index
using the `level` parameter:

>>> arrays = [['Falcon', 'Falcon', 'Parrot', 'Parrot'],
...           ['Captive', 'Wild', 'Captive', 'Wild']]
>>> index = pd.MultiIndex.from_arrays(arrays, names=('Animal', 'Type'))
>>> ser = pd.Series([390., 350., 30., 20.], index=index, name="Max Speed")
>>> ser
Animal  Type
Falcon  Captive    390.0
        Wild       350.0
Parrot  Captive     30.0
        Wild        20.0
Name: Max Speed, dtype: float64
>>> ser.groupby(level=0).mean()
Animal
Falcon    370.0
Parrot     25.0
Name: Max Speed, dtype: float64
>>> ser.groupby(level="Type").mean()
Type
Captive    210.0
Wild       185.0
Name: Max Speed, dtype: float64

We can also choose to include `NA` in group keys or not by defining
`dropna` parameter, the default setting is `True`.

>>> ser = pd.Series([1, 2, 3, 3], index=["a", 'a', 'b', np.nan])
>>> ser.groupby(level=0).sum()
a    3
b    3
dtype: int64

>>> ser.groupby(level=0, dropna=False).sum()
a    3
b    3
NaN  3
dtype: int64

>>> arrays = ['Falcon', 'Falcon', 'Parrot', 'Parrot']
>>> ser = pd.Series([390., 350., 30., 20.], index=arrays, name="Max Speed")
>>> ser.groupby(["a", "b", "a", np.nan]).mean()
a    210.0
b    350.0
Name: Max Speed, dtype: float64

>>> ser.groupby(["a", "b", "a", np.nan], dropna=False).mean()
a    210.0
b    350.0
NaN   20.0
Name: Max Speed, dtype: float64
File:      c:\users\konta\anaconda3\envs\ds\lib\site-packages\pandas\core\series.py
Type:      method

In [67]:
data.loc['2023-01']

Date
2023-01-03    14.300684
2023-01-04    14.734250
2023-01-05    14.250734
2023-01-06    14.844139
2023-01-09    15.612370
2023-01-10    15.893089
2023-01-11    15.984997
2023-01-12    16.494484
2023-01-13    16.882099
2023-01-17    17.684299
2023-01-18    17.359623
2023-01-19    16.748234
2023-01-20    17.821161
2023-01-23    19.173803
2023-01-24    19.245733
2023-01-25    19.303675
2023-01-26    19.782194
2023-01-27    20.344635
2023-01-30    19.142836
2023-01-31    19.517462
Name: Close, dtype: float64

In [68]:
data.loc['2023-12':'2024-12']

Date
2023-12-01     46.734852
2023-12-04     45.480659
2023-12-05     46.540070
2023-12-06     45.477661
2023-12-07     46.570061
                 ...
2024-12-24    140.181656
2024-12-26    139.891739
2024-12-27    136.972519
2024-12-30    137.452393
2024-12-31    134.253281
Name: Close, Length: 272, dtype: float64

In [ ]:
data.between_time('2023-12', '2024-03')

Date
2023-01-03     14.300684
2023-01-04     14.734250
2023-01-05     14.250734
2023-01-06     14.844139
2023-01-09     15.612370
                 ...
2025-12-15    176.289993
2025-12-16    177.720001
2025-12-17    170.940002
2025-12-18    174.139999
2025-12-19    180.990005
Name: Close, Length: 745, dtype: float64

In [1]:
%pip install seaborn

Requirement already satisfied: seaborn in c:\users\konta\anaconda3\envs\ds\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\konta\anaconda3\envs\ds\lib\site-packages (from seaborn) (2.3.4)
Requirement already satisfied: pandas>=1.2 in c:\users\konta\anaconda3\envs\ds\lib\site-packages (from seaborn) (2.3.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\konta\anaconda3\envs\ds\lib\site-packages (from seaborn) (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\konta\anaconda3\envs\ds\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\konta\anaconda3\envs\ds\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\konta\anaconda3\envs\ds\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\konta\anaconda3\envs\ds\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\konta\anaconda3\envs\ds\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\konta\anaconda3\envs\ds\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.0.0)
Requirement already satisfied: pyparsing>=3 in c:\users\konta\anaconda3\envs\ds\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\konta\anaconda3\envs\ds\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\konta\anaconda3\envs\ds\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\konta\anaconda3\envs\ds\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\konta\anaconda3\envs\ds\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
%pip install matplotlib

Requirement already satisfied: matplotlib in c:\users\konta\anaconda3\envs\ds\lib\site-packages (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\konta\anaconda3\envs\ds\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\konta\anaconda3\envs\ds\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\konta\anaconda3\envs\ds\lib\site-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\konta\anaconda3\envs\ds\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: numpy>=1.23 in c:\users\konta\anaconda3\envs\ds\lib\site-packages (from matplotlib) (2.3.4)
Requirement already satisfied: packaging>=20.0 in c:\users\konta\anaconda3\envs\ds\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\konta\anaconda3\envs\ds\lib\site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=3 in c:\users\konta\anaconda3\envs\ds\lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\konta\anaconda3\envs\ds\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\konta\anaconda3\envs\ds\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import pandas as pd

def combine_two_tables(person: pd.DataFrame, address: pd.DataFrame) -> pd.DataFrame:
    pass
pd.merge?

Signature:
pd.merge(
    left: 'DataFrame | Series',
    right: 'DataFrame | Series',
    how: 'MergeHow' = 'inner',
    on: 'IndexLabel | AnyArrayLike | None' = None,
    left_on: 'IndexLabel | AnyArrayLike | None' = None,
    right_on: 'IndexLabel | AnyArrayLike | None' = None,
    left_index: 'bool' = False,
    right_index: 'bool' = False,
    sort: 'bool' = False,
    suffixes: 'Suffixes' = ('_x', '_y'),
    copy: 'bool | None' = None,
    indicator: 'str | bool' = False,
    validate: 'str | None' = None,
) -> 'DataFrame'
Docstring:
Merge DataFrame or named Series objects with a database-style join.

A named Series object is treated as a DataFrame with a single named column.

The join is done on columns or indexes. If joining columns on
columns, the DataFrame indexes *will be ignored*. Otherwise if joining indexes
on indexes or indexes on a column or columns, the index will be passed on.
When performing a cross merge, no column specifications to merge on are
allowed.

.. warning::

    If both key columns contain rows where the key is a null value, those
    rows will be matched against each other. This is different from usual SQL
    join behaviour and can lead to unexpected results.

Parameters
----------
left : DataFrame or named Series
right : DataFrame or named Series
    Object to merge with.
how : {'left', 'right', 'outer', 'inner', 'cross'}, default 'inner'
    Type of merge to be performed.

    * left: use only keys from left frame, similar to a SQL left outer join;
      preserve key order.
    * right: use only keys from right frame, similar to a SQL right outer join;
      preserve key order.
    * outer: use union of keys from both frames, similar to a SQL full outer
      join; sort keys lexicographically.
    * inner: use intersection of keys from both frames, similar to a SQL inner
      join; preserve the order of the left keys.
    * cross: creates the cartesian product from both frames, preserves the order
      of the left keys.
on : label or list
    Column or index level names to join on. These must be found in both
    DataFrames. If `on` is None and not merging on indexes then this defaults
    to the intersection of the columns in both DataFrames.
left_on : label or list, or array-like
    Column or index level names to join on in the left DataFrame. Can also
    be an array or list of arrays of the length of the left DataFrame.
    These arrays are treated as if they are columns.
right_on : label or list, or array-like
    Column or index level names to join on in the right DataFrame. Can also
    be an array or list of arrays of the length of the right DataFrame.
    These arrays are treated as if they are columns.
left_index : bool, default False
    Use the index from the left DataFrame as the join key(s). If it is a
    MultiIndex, the number of keys in the other DataFrame (either the index
    or a number of columns) must match the number of levels.
right_index : bool, default False
    Use the index from the right DataFrame as the join key. Same caveats as
    left_index.
sort : bool, default False
    Sort the join keys lexicographically in the result DataFrame. If False,
    the order of the join keys depends on the join type (how keyword).
suffixes : list-like, default is ("_x", "_y")
    A length-2 sequence where each element is optionally a string
    indicating the suffix to add to overlapping column names in
    `left` and `right` respectively. Pass a value of `None` instead
    of a string to indicate that the column name from `left` or
    `right` should be left as-is, with no suffix. At least one of the
    values must not be None.
copy : bool, default True
    If False, avoid copy if possible.

    .. note::
        The `copy` keyword will change behavior in pandas 3.0.
        `Copy-on-Write
        <https://pandas.pydata.org/docs/dev/user_guide/copy_on_write.html>`__
        will be enabled by default, which means that all methods with a
        `copy` keyword will use a lazy copy mechanism to defer the copy and
        ignore the `copy` keyword. The `copy` keyword will be removed in a
        future version of pandas.

        You can already get the future behavior and improvements through
        enabling copy on write ``pd.options.mode.copy_on_write = True``
indicator : bool or str, default False
    If True, adds a column to the output DataFrame called "_merge" with
    information on the source of each row. The column can be given a different
    name by providing a string argument. The column will have a Categorical
    type with the value of "left_only" for observations whose merge key only
    appears in the left DataFrame, "right_only" for observations
    whose merge key only appears in the right DataFrame, and "both"
    if the observation's merge key is found in both DataFrames.

validate : str, optional
    If specified, checks if merge is of specified type.

    * "one_to_one" or "1:1": check if merge keys are unique in both
      left and right datasets.
    * "one_to_many" or "1:m": check if merge keys are unique in left
      dataset.
    * "many_to_one" or "m:1": check if merge keys are unique in right
      dataset.
    * "many_to_many" or "m:m": allowed, but does not result in checks.

Returns
-------
DataFrame
    A DataFrame of the two merged objects.

See Also
--------
merge_ordered : Merge with optional filling/interpolation.
merge_asof : Merge on nearest keys.
DataFrame.join : Similar method using indices.

Examples
--------
>>> df1 = pd.DataFrame({'lkey': ['foo', 'bar', 'baz', 'foo'],
...                     'value': [1, 2, 3, 5]})
>>> df2 = pd.DataFrame({'rkey': ['foo', 'bar', 'baz', 'foo'],
...                     'value': [5, 6, 7, 8]})
>>> df1
    lkey value
0   foo      1
1   bar      2
2   baz      3
3   foo      5
>>> df2
    rkey value
0   foo      5
1   bar      6
2   baz      7
3   foo      8

Merge df1 and df2 on the lkey and rkey columns. The value columns have
the default suffixes, _x and _y, appended.

>>> df1.merge(df2, left_on='lkey', right_on='rkey')
  lkey  value_x rkey  value_y
0  foo        1  foo        5
1  foo        1  foo        8
2  bar        2  bar        6
3  baz        3  baz        7
4  foo        5  foo        5
5  foo        5  foo        8

Merge DataFrames df1 and df2 with specified left and right suffixes
appended to any overlapping columns.

>>> df1.merge(df2, left_on='lkey', right_on='rkey',
...           suffixes=('_left', '_right'))
  lkey  value_left rkey  value_right
0  foo           1  foo            5
1  foo           1  foo            8
2  bar           2  bar            6
3  baz           3  baz            7
4  foo           5  foo            5
5  foo           5  foo            8

Merge DataFrames df1 and df2, but raise an exception if the DataFrames have
any overlapping columns.

>>> df1.merge(df2, left_on='lkey', right_on='rkey', suffixes=(False, False))
Traceback (most recent call last):
...
ValueError: columns overlap but no suffix specified:
    Index(['value'], dtype='object')

>>> df1 = pd.DataFrame({'a': ['foo', 'bar'], 'b': [1, 2]})
>>> df2 = pd.DataFrame({'a': ['foo', 'baz'], 'c': [3, 4]})
>>> df1
      a  b
0   foo  1
1   bar  2
>>> df2
      a  c
0   foo  3
1   baz  4

>>> df1.merge(df2, how='inner', on='a')
      a  b  c
0   foo  1  3

>>> df1.merge(df2, how='left', on='a')
      a  b  c
0   foo  1  3.0
1   bar  2  NaN

>>> df1 = pd.DataFrame({'left': ['foo', 'bar']})
>>> df2 = pd.DataFrame({'right': [7, 8]})
>>> df1
    left
0   foo
1   bar
>>> df2
    right
0   7
1   8

>>> df1.merge(df2, how='cross')
   left  right
0   foo      7
1   foo      8
2   bar      7
3   bar      8
File:      c:\users\konta\anaconda3\envs\ds\lib\site-packages\pandas\core\reshape\merge.py
Type:      function

Object `pd.groupby` not found.