### Exercise 1: Create a DataFrame from a Dictionary

In [4]:
import pandas as pd

Dict = {
    'Product': ['Apples', 'Oranges', 'Bananas'],
    'Price': [1.5, 1.2, 1.8],
    'InStock': [True, True, False]
}

Df_Dict = pd.DataFrame(data=Dict)

Df_Dict

   Product  Price  InStock
0   Apples    1.5     True
1  Oranges    1.2     True
2  Bananas    1.8    False

### Exercise 2: Create a DataFrame from a List of Lists

In [15]:
List = [[1, 'Alice', 100000], [2, 'Bob', 80000], [3, 'Charlie', 120000]]
Index_Col = ['ID', 'Name', 'Salary']

Df = pd.DataFrame(data=List, columns=Index_Col)

Df

   ID     Name  Salary
0   1    Alice  100000
1   2      Bob   80000
2   3  Charlie  120000

### Exercise 3: CSV File I/O

In [7]:
Df_Dict.to_csv('products.csv', index=False)

In [14]:
df_from_csv = pd.read_csv('products.csv')
df_from_csv

   Product  Price  InStock
0   Apples    1.5     True
1  Oranges    1.2     True
2  Bananas    1.8    False

### Exercise 4: Excel File I/O

In [12]:
Df.to_excel('employees.xlsx', sheet_name='EmployeeData', index=False)

In [13]:
df_from_xlsx = pd.read_excel('employees.xlsx')
df_from_xlsx

   ID     Name  Salary
0   1    Alice  100000
1   2      Bob   80000
2   3  Charlie  120000

### Exercise 5: Create a Multi-Index DataFrame

In [6]:
data = {
    ('Q1', 'Sales'): {('USA', 'East'): 100, ('USA', 'West'): 120, ('EU', 'North'): 80},
    ('Q1', 'Profit'): {('USA', 'East'): 20, ('USA', 'West'): 25, ('EU', 'North'): 15},
    ('Q2', 'Sales'): {('USA', 'East'): 110, ('USA', 'West'): 130, ('EU', 'North'): 90},
    ('Q2', 'Profit'): {('USA', 'East'): 22, ('USA', 'West'): 28, ('EU', 'North'): 18}
}

df_from_data = pd.DataFrame(data=data)

df_from_data

             Q1           Q2
          Sales Profit Sales Profit
USA East    100     20   110     22
    West    120     25   130     28
EU  North    80     15    90     18

### Exercise 6: Accessing Data in a Multi-Index DataFrame

In [21]:
df_from_data['Q1']

           Sales  Profit
USA East     100      20
    West     120      25
EU  North     80      15

In [30]:
df_from_data['Q1', 'Profit']

USA  East     20
     West     25
EU   North    15
Name: (Q1, Profit), dtype: int64

In [28]:
df_from_data.loc['USA']

        Q1           Q2
     Sales Profit Sales Profit
East   100     20   110     22
West   120     25   130     28

### Exercise 7: Stacking

In [7]:
new_data = df_from_data.stack(future_stack=True)
print(new_data)

                   Q1   Q2
USA East  Sales   100  110
          Profit   20   22
    West  Sales   120  130
          Profit   25   28
EU  North Sales    80   90
          Profit   15   18

### Exercise 8: Unstacking

In [8]:
new_data.unstack(level=0)

                Q1           Q2
                EU    USA    EU    USA
East  Sales    NaN  100.0   NaN  110.0
      Profit   NaN   20.0   NaN   22.0
North Sales   80.0    NaN  90.0    NaN
      Profit  15.0    NaN  18.0    NaN
West  Sales    NaN  120.0   NaN  130.0
      Profit   NaN   25.0   NaN   28.0

### Exercise 9: Renaming Columns and Setting Index

In [15]:
data = {
    'Country': ['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola'],
    'Code': ['AFG', 'ALB', 'DZA', 'AND', 'AGO'],
    'Continent': ['Asia', 'Europe', 'Africa', 'Europe', 'Africa'],
    'Population': [41128771, 2842321, 44903225, 79034, 35588987]
}
df_countries = pd.DataFrame(data)

x = df_countries.rename({'Code': 'ISO_Code'}, axis='columns')
new_df_countries = x.set_index('Country')
new_df_countries

            ISO_Code Continent  Population
Country
Afghanistan      AFG      Asia    41128771
Albania          ALB    Europe     2842321
Algeria          DZA    Africa    44903225
Andorra          AND    Europe       79034
Angola           AGO    Africa    35588987

### Exercise 10: Multi-Index and Sorting

In [31]:
y = new_df_countries.reset_index()
y

       Country ISO_Code Continent  Population
0  Afghanistan      AFG      Asia    41128771
1      Albania      ALB    Europe     2842321
2      Algeria      DZA    Africa    44903225
3      Andorra      AND    Europe       79034
4       Angola      AGO    Africa    35588987

In [36]:
final_indexed = y.set_index(['Country', 'Continent'])
final_indexed

                      ISO_Code  Population
Country     Continent
Afghanistan Asia           AFG    41128771
Albania     Europe         ALB     2842321
Algeria     Africa         DZA    44903225
Andorra     Europe         AND       79034
Angola      Africa         AGO    35588987

In [38]:
Sorted = final_indexed.sort_index()

Sorted

                      ISO_Code  Population
Country     Continent
Afghanistan Asia           AFG    41128771
Albania     Europe         ALB     2842321
Algeria     Africa         DZA    44903225
Andorra     Europe         AND       79034
Angola      Africa         AGO    35588987

### Exercise 11: Resetting Index

In [39]:
Sorted.reset_index()

       Country Continent ISO_Code  Population
0  Afghanistan      Asia      AFG    41128771
1      Albania    Europe      ALB     2842321
2      Algeria    Africa      DZA    44903225
3      Andorra    Europe      AND       79034
4       Angola    Africa      AGO    35588987